<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ApplicationIcon>..\tools\icon.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>ntl-studio</AssemblyName>
    <RootNamespace>Neutraled.Studio</RootNamespace>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
  </PropertyGroup>

</Project>
