namespace Neutraled.Builder;

/// <summary>英文译文表（Tools 组）。key = 中文原文（含 {0} 占位符），value = 英文。
/// 由 tools 脚本从 _i18n-builder/keys-tools.json 生成，**不要手改单个条目**。</summary>
public static class LangTable_Tools
{
    public static void Fill(Dictionary<string, string> d)
    {
        d["\n  [共存] {0}\n          {1}"] = "\n  [Coexist] {0}\n          {1}";
        d["\n  [冲突] {0}\n          {1}"] = "\n  [Conflict] {0}\n          {1}";
        d["\n  [覆盖] {0}\n          {1}"] = "\n  [Override] {0}\n          {1}";
        d["\n--- 警告 {0} 个（建议修）---"] = "\n--- {0} warnings (recommended to fix) ---";
        d["\n--- 错误 {0} 个（必须修）---"] = "\n--- {0} errors (must fix) ---";
        d["\n合计: {0} 错误 / {1} 警告"] = "\nTotal: {0} errors / {1} warnings";
        d["           - {0}  (来源 {1}, 作者 {2})"] = "           - {0}  (source {1}, author {2})";
        d["           - {0}（来源 {1}，作者 {2}）"] = "           - {0} (source {1}, author {2})";
        d["           1) 先正常进一次第 "] = "           1) First launch chapter ";
        d["           2) 用 --import-bside <一份真实的B面存档> --chapter "] = "           2) Use --import-bside <a real B-side save> --chapter ";
        d["         两条路任选："] = "         Pick either path:";
        d["      ...还有 {0} 个"] = "      ...and {0} more";
        d["      样例 '{0}': {1}x{2} @({3},{4}) Shift={5} Offset={6}"] = "      Sample '{0}': {1}x{2} @({3},{4}) Shift={5} Offset={6}";
        d["    [未声明] {0}: "] = "    [Undeclared] {0}: ";
        d["    [漏] "] = "    [Missed] ";
        d["    [警告] raw 替换目标不存在: {0}（{1}）"] = "    [Warning] raw replace target does not exist: {0} ({1})";
        d["    [警告] tileset 缺失: {0}（该部分图块将留空）"] = "    [Warning] tileset missing: {0} (those tiles will be left blank)";
        d["    [警告] {0}: 找不到页图 {1}"] = "    [Warning] {0}: page image {1} not found";
        d["    [警告] {0}: 新实现里没有 function {1}()，可能无法被调用"] = "    [Warning] {0}: the new implementation has no function {1}(), it may not be callable";
        d["    [警告] {0}: 页图尺寸读不出来"] = "    [Warning] {0}: cannot read the page image size";
        d["    [警告] 帧缺失: {0}"] = "    [Warning] frame missing: {0}";
        d["    [警告] 无法解析章节声明: "] = "    [Warning] cannot parse chapter declaration: ";
        d["    [警告] 没有任何条目被替换 —— 若目标里本该有同名对象，说明复制成了新增而不是覆盖（会静默失效）"] = "    [Warning] no entries were replaced -- if the target was supposed to have an object with the same name, the copy was added instead of overwriting (it will silently do nothing)";
        d["    [警告] 源缺少代码对象: {0}"] = "    [Warning] source is missing code object: {0}";
        d["    [警告] 解析失败 {0}: {1}"] = "    [Warning] parse failed {0}: {1}";
        d["    [警告] 读取失败 {0}: {1}"] = "    [Warning] read failed {0}: {1}";
        d["    [警告] 读图失败 {0}: {1}"] = "    [Warning] image read failed {0}: {1}";
        d["    [警告] 音频缺失: {0}"] = "    [Warning] audio missing: {0}";
        d["    [跳过] {0}（基底已改动，未声明 override）"] = "    [Skip] {0} (base was modified without declaring override)";
        d["    [跳过] 无 json 定义"] = "    [Skip] no json definition";
        d["    [跳过] 无有效定义"] = "    [Skip] no valid definition";
        d["    [错误] raw 替换失败 {0}: {1}"] = "    [Error] raw replace failed {0}: {1}";
        d["    raw 替换: {0}（来自 {1}）"] = "    raw replace: {0} (from {1})";
        d["    {0,-16} {1,4} 个   ({2}{3})"] = "    {0,-16} {1,4}     ({2}{3})";
        d["    {0,-16} {1,4} 个（{2} 有文档）"] = "    {0,-16} {1,4}     ({2} documented)";
        d["    …已渲染 {0} 个字形"] = "    ...rendered {0} glyphs";
        d["    函数修复: {0} 个补齐 Occurrences"] = "    Function repair: {0} had Occurrences filled in";
        d["    声音: {0} 新增 / {1} 替换 / {2} 跳过"] = "    Sounds: {0} added / {1} replaced / {2} skipped";
        d["    字体: {0} {1} 字形，纹理页 {2}x{3}"] = "    Font: {0} {1} glyphs, texture page {2}x{3}";
        d["    字体: {0} {1} 字形，纹理页 {2}x{3}（预拼页直用，{4}ms）"] = "    Font: {0} {1} glyphs, texture page {2}x{3} (prebuilt page used as-is, {4}ms)";
        d["    引用复制: {0} 个代码对象（其中 {1} 个是**替换**已有条目）/ {2} 跳过（函数补 {3} 个）"] = "    Reference copy: {0} code objects ({1} of them **replace** existing entries) / {2} skipped ({3} functions filled in)";
        d["    精灵: {0} 新增 / {1} 帧替换 / {2} 跳过（纹理页 {3} 张）"] = "    Sprites: {0} added / {1} frames replaced / {2} skipped ({3} texture pages)";
        d["  --- UndertaleInstruction 关键字段的真实类型 ---"] = "  --- Real types of key UndertaleInstruction fields ---";
        d["  --- 复刻 CopyInstruction 的完整 initializer 顺序 ---"] = "  --- Full initializer order for replicating CopyInstruction ---";
        d["  ...（共 {0} 条，只显示前 {1} 条）"] = "  ...({0} total, showing only the first {1})";
        d["  API 分组:"] = "  API groups:";
        d["  API 注册表: 函数 {0} / 对象 {1} / "] = "  API registry: functions {0} / objects {1} / ";
        d["  B 面模板已导入: {0}（{1} 行）"] = "  B-side template imported: {0} ({1} lines)";
        d["  CodeLocals 去重: {0} 个"] = "  CodeLocals dedup: {0}";
        d["  Neutraled 自检 (selftest)"] = "  Neutraled self-test (selftest)";
        d["  [命中] {0}  属性 {1} ({2}) = {3}"] = "  [Hit] {0}  property {1} ({2}) = {3}";
        d["  [外部章节] {0} → {1}（--add-external 注册）"] = "  [External chapter] {0} -> {1} (registered with --add-external)";
        d["  [外部章节] {0}: {1} → {2}（选中时退出游戏并启动它）"] = "  [External chapter] {0}: {1} -> {2} (exits the game and launches it when selected)";
        d["  [官方修改] {0}: Chapter:{1}（叠加到官方第 {2} 章，不产生章节条目）"] = "  [Official edit] {0}: Chapter:{1} (layered onto official chapter {2}, no chapter entry is created)";
        d["  [提示] 没写出控制台日志（找过 {0}）—— 说明钩子没生效"] = "  [Tip] no console log was written (looked in {0}) -- this means the hook did not take effect";
        d["  [时间线修改] {0}: Chapter:{1}:{2} → 并入 {3}"] = "  [Timeline edit] {0}: Chapter:{1}:{2} -> merged into {3}";
        d["  [警告] "] = "  [Warning] ";
        d["  [警告] hook 目标脚本不存在: {0}"] = "  [Warning] hook target script does not exist: {0}";
        d["  [警告] 章节 {0} 引用「{1}」未找到匹配来源"] = "  [Warning] chapter {0} reference '{1}' has no matching source";
        d["  [警告] 章节 {0} 的引用「{1}」有 {2} 个同名来源，请用 @mod名 / @mod名:作者 / #序列 消歧："] = "  [Warning] chapter {0} reference '{1}' has {2} sources with the same name; disambiguate with @modname / @modname:author / #index:";
        d["  [警告] 缓存索引读取失败: {0}"] = "  [Warning] failed to read the cache index: {0}";
        d["  [警告] 读外部章节清单失败: "] = "  [Warning] failed to read the external chapter list: ";
        d["  [跳过] {0}: 反编译失败（{1}）"] = "  [Skip] {0}: decompile failed ({1})";
        d["  [跳过] {0}: 已包装过"] = "  [Skip] {0}: already wrapped";
        d["  [跳过] {0}: 脚本里找不到 function {1}(，无法包装"] = "  [Skip] {0}: cannot find function {1}( in the script, cannot wrap";
        d["  [错误] 20 秒内没等到窗口"] = "  [Error] no window appeared within 20 seconds";
        d["  [错误] xdelta 应用失败 (exit={0}): {1}"] = "  [Error] xdelta apply failed (exit={0}): {1}";
        d["  [错误] zip 内无 chapter{0} 补丁，可用: {1}"] = "  [Error] no chapter{0} patch inside the zip, available: {1}";
        d["  [错误] zip 内未找到 .xdelta 或 data.win"] = "  [Error] no .xdelta or data.win found in the zip";
        d["  [错误] {0}: 「Chapter:{1}:{2}」找不到对应的平行时间线"] = "  [Error] {0}: no matching parallel timeline for 'Chapter:{1}:{2}'";
        d["  [错误] {0}: 「Chapter:{1}:{2}」有 {3} 个同名平行时间线，请用 @来源mod / @mod:作者 / #序列 消歧："] = "  [Error] {0}: 'Chapter:{1}:{2}' has {3} parallel timelines with the same name; disambiguate with @sourcemod / @mod:author / #index:";
        d["  [错误] {0}: 「~Chapter:{1}」缺少章节名 —— "] = "  [Error] {0}: '~Chapter:{1}' is missing a chapter name -- ";
        d["  [错误] 存档不存在: {0}"] = "  [Error] save does not exist: {0}";
        d["  [错误] 找不到 api/ 目录"] = "  [Error] api/ directory not found";
        d["  [错误] 找不到 {0}"] = "  [Error] cannot find {0}";
        d["  [错误] 找不到窗口"] = "  [Error] window not found";
        d["  [错误] 未找到 xdelta3.exe"] = "  [Error] xdelta3.exe not found";
        d["  [错误] 目录内未找到可识别的 xdelta / data.win"] = "  [Error] no recognizable xdelta / data.win found in the directory";
        d["  [错误] 第 "] = "  [Error] Chapter ";
        d["  [错误] 缺少原版基线: {0}"] = "  [Error] missing vanilla baseline: {0}";
        d["  hook 包装: {0} -> {1}（模式: {2}）"] = "  hook wrap: {0} -> {1} (mode: {2})";
        d["  hook 注册表: {0} 条 -> {1}"] = "  hook registry: {0} entries -> {1}";
        d["  sheet {0}/{1}: {2} 字形, {3}x{4}"] = "  sheet {0}/{1}: {2} glyphs, {3}x{4}";
        d["  {0}（{1}）:"] = "  {0} ({1}):";
        d["  ✅ 全部检查通过，没有发现问题"] = "  ✅ all checks passed, no problems found";
        d["  ✅ 所有 API 都健康"] = "  ✅ all APIs are healthy";
        d["  ✅ 没有发现问题"] = "  ✅ no problems found";
        d["  ✓ 无漏（快判据可用）"] = "  ✓ no misses (fast check usable)";
        d["  ✗ 有漏！"] = "  ✗ misses found!";
        d["  ❌ 可疑 API（{0}）:"] = "  ❌ suspicious APIs ({0}):";
        d["  与目标一致: {0}   当前窗口={1}"] = "  Matches target: {0}   current window={1}";
        d["  中文字体: 字符集={0} 共 {1} 个字符，源字体={2}，字号={3}"] = "  CJK font: charset={0}, {1} characters, source font={2}, size={3}";
        d["  临时文件清理: {0:F1} MB"] = "  Temp file cleanup: {0:F1} MB";
        d["  产物: 对象={0} 代码={1} 精灵={2} 声音={3}"] = "  Output: objects={0} code={1} sprites={2} sounds={3}";
        d["  依赖自动启用: {0} 个"] = "  Dependencies auto-enabled: {0}";
        d["  冲突分析: {0} 个冲突 / {1} 个覆盖 / {2} 个可共存"] = "  Conflict analysis: {0} conflicts / {1} overrides / {2} can coexist";
        d["  冲突分析: 未发现 mod 之间的冲突"] = "  Conflict analysis: no conflicts found between mods";
        d["  函数引用修复: {0} 个"] = "  Function reference fixes: {0}";
        d["  分组:"] = "  Groups:";
        d["  发现: {0}（共 {1} 个补丁）"] = "  Found: {0} ({1} patches total)";
        d["  发送时前台: {0}"] = "  Foreground at send time: {0}";
        d["  复制修改版 data.win"] = "  Copy the modified data.win";
        d["  外部文件: {0} 个"] = "  External files: {0}";
        d["  多出: {0}（安全）"] = "  Extra: {0} (safe)";
        d["  字体包已写入 {0}（{1} 字形 / {2} 张 sheet）"] = "  Font pack written to {0} ({1} glyphs / {2} sheets)";
        d["  已写入 B 面存档: "] = "  B-side save written: ";
        d["  已把现有存档标记为 B 面: "] = "  Marked the existing save as B-side: ";
        d["  已标记 dr.ini SideB=1（章节 "] = "  Marked dr.ini SideB=1 (chapter ";
        d["  已生成 mod: {0}"] = "  Mod generated: {0}";
        d["  已结束测试进程（--keep 可保留）"] = "  Test process ended (use --keep to keep it)";
        d["  应用 xdelta: {0}"] = "  Applying xdelta: {0}";
        d["  循环依赖: {0}"] = "  Circular dependencies: {0}";
        d["  扫描: {0}"] = "  Scanning: {0}";
        d["  找到 {0} 个 ntl_* 脚本，call_host 里分派了 {1} 个名字"] = "  Found {0} ntl_* scripts; {1} names dispatched in call_host";
        d["  抢焦点结果: {0}   （pid={1}）"] = "  Focus grab result: {0}   (pid={1})";
        d["  指令 "] = "  Instruction ";
        d["  指令 {0} / 参数 {1} / 局部 {2}"] = "  Instructions {0} / arguments {1} / locals {2}";
        d["  控制台日志 {0}（最后 {1} 行）:"] = "  Console log {0} (last {1} lines):";
        d["  提示：对象名形如 gml_GlobalScript_xxx / gml_Object_obj_xxx_Step_0"] = "  Tip: object names look like gml_GlobalScript_xxx / gml_Object_obj_xxx_Step_0";
        d["  提示：该补丁可能基于其它游戏版本，请从 GameBanana 下载适配当前版本的补丁"] = "  Tip: this patch may target another game version; download a patch for your version from GameBanana";
        d["  搬字形完成: {0} 个（跳过 {1}），页 {2}x{3}"] = "  Glyphs moved: {0} (skipped {1}), pages {2}x{3}";
        d["  无文档:   {0}"] = "  Undocumented: {0}";
        d["  有文档:   {0}"] = "  Documented:   {0}";
        d["  权限分析: {0} 个 mod 需要关注"] = "  Permission analysis: {0} mods need attention";
        d["  权限分析: 所有 mod 都没有敏感操作"] = "  Permission analysis: no mod performs sensitive operations";
        d["  样张失败 {0}: {1}"] = "  Sample render failed {0}: {1}";
        d["  测试前前台: {0}"] = "  Foreground before test: {0}";
        d["  测试后前台: {0}"] = "  Foreground after test: {0}";
        d["  渲染: 全宽 {0} 个（每批 {1}），窄体 {2} 个"] = "  Render: {0} full-width (batch size {1}), {2} narrow";
        d["  渲染完成: {0} 个字形"] = "  Render complete: {0} glyphs";
        d["  源字体: {0}  EmSize={1} AA={2} 字形={3}"] = "  Source font: {0}  EmSize={1} AA={2} glyphs={3}";
        d["  源纹理页已原样导出: {0} {1}x{2}（字形坐标不改）"] = "  Source texture page exported as-is: {0} {1}x{2} (glyph coordinates unchanged)";
        d["  漏掉: {0}"] = "  Missed: {0}";
        d["  用【文本通道】输入 \"{0}\" + 回车 …"] = "  Type '{0}' via the [text channel] + Enter ...";
        d["  用【键盘通道】输入 \"{0}\" + 回车（模拟输入法开着）…"] = "  Type '{0}' via the [keyboard channel] + Enter (simulating an active IME) ...";
        d["  目标窗口:   {0}"] = "  Target window:   {0}";
        d["  相近的对象: "] = "  Similar objects: ";
        d["  章节引用: {0} -> 基于 {1}（产物独立）"] = "  Chapter reference: {0} -> based on {1} (independent output)";
        d["  章节注册表: {0} 条 -> {1}"] = "  Chapter registry: {0} entries -> {1}";
        d["  等引擎启动完成后敲 F2（真键盘，和玩家按的一样）…"] = "  Once the engine has finished starting, press F2 (a real keypress, same as the player's) ...";
        d["  统计: {0} 错误 / {1} 警告 / {2} 提示"] = "  Summary: {0} errors / {1} warnings / {2} tips";
        d["  统计: {0}/{1} 正常，{2} 可疑"] = "  Summary: {0}/{1} OK, {2} suspicious";
        d["  缓存去重: 合并 {0} 个文件，节省 {1} MB"] = "  Cache dedup: merged {0} files, saved {1} MB";
        d["  缓存已保存: {0} ({1} MB, 目标 {2} 个)"] = "  Cache saved: {0} ({1} MB, {2} targets)";
        d["  缓存淘汰: {0} (释放 {1} MB)"] = "  Cache evicted: {0} (freed {1} MB)";
        d["  缺失 child 函数补齐: {0} 个"] = "  Missing child functions filled in: {0}";
        d["  缺失依赖: {0} 个（这些 mod 可能无法正常工作）"] = "  Missing dependencies: {0} (these mods may not work correctly)";
        d["  脚本总数: {0}"] = "  Total scripts: {0}";
        d["  输出: {0}"] = "  Output: {0}";
        d["  运行时注册表: mod {0} -> {1} ({2} KB)"] = "  Runtime registry: mod {0} -> {1} ({2} KB)";
        d["  进程保留中 pid={0}"] = "  Process kept alive, pid={0}";
        d[" 个槽位既无模板也无存档，已跳过"] = " slots had neither a template nor a save; skipped";
        d[" 导入模板后，可一键生成任意槽位"] = " to import a template; after that any slot can be generated in one go";
        d[" 槽位 "] = " slot ";
        d[" 章既没有 B 面模板、也没有现成存档，无法凭空造一个（标记与内容必须一致）"] = " has neither a B-side template nor an existing save; one cannot be created out of thin air (the marker and the content must match)";
        d[" 章（游戏会生成该槽位存档），再跑一次本命令 → 会把它标记成 B 面"] = " normally (the game will create that slot's save), then run this command again -> it will be marked as B-side";
        d["--- 转换 {0}: {1} ---"] = "--- Converting {0}: {1} ---";
        d["===== API 冒烟测试 (smoke) ====="] = "===== API smoke test (smoke) =====";
        d["===== API 文档生成 ====="] = "===== API doc generation =====";
        d["===== Neutraled 自检 (doctor) ====="] = "===== Neutraled self-check (doctor) =====";
        d["===== Neutraled 静态检查 (lint) ====="] = "===== Neutraled static check (lint) =====";
        d["===== 焦点抢占自检 ====="] = "===== Focus grab self-check =====";
        d["===== 结果 ====="] = "===== Results =====";
        d["===== 自检结果: {0}/{1} 通过 ====="] = "===== Self-check results: {0}/{1} passed =====";
        d["A 慢（反编译文本）: {0} 个，{1:N1}s"] = "A slow (decompiled text): {0}, {1:N1}s";
        d["B 快（指令操作数）: {0} 个，{1:N2}s"] = "B fast (instruction operands): {0}, {1:N2}s";
        d["PNG 尺寸必须为正"] = "PNG dimensions must be positive";
        d["RGBA 缓冲区长度与尺寸不符"] = "RGBA buffer length does not match the dimensions";
        d["[1/7] 宿主函数完整性..."] = "[1/7] Host function integrity...";
        d["[2/7] 脚本完整性..."] = "[2/7] Script integrity...";
        d["[3/7] 不可达代码..."] = "[3/7] Unreachable code...";
        d["[4/7] 变量定义..."] = "[4/7] Variable definitions...";
        d["[5/7] 部署目标一致性..."] = "[5/7] Deploy target consistency...";
        d["[6/7] mod 加载..."] = "[6/7] mod loading...";
        d["[7/7] 异常处理..."] = "[7/7] Exception handling...";
        d["[错误] 找不到 api/"] = "[Error] api/ not found";
        d["[错误] 找不到: "] = "[Error] not found: ";
        d["[错误] 找不到代码对象: "] = "[Error] code object not found: ";
        d["⚠️ {0}（{1}）"] = "⚠️ {0} ({1})";
        d["✓ 图标已生成: {0}（{1} 个尺寸，{2} KB）"] = "✓ Icon generated: {0} ({1} sizes, {2} KB)";
        d["一个字形都没搬过来"] = "Not a single glyph was moved over";
        d["代码对象: {0}"] = "Code objects: {0}";
        d["地图尺寸无效"] = "Invalid map size";
        d["字体 {0} 没有可用的纹理页"] = "Font {0} has no usable texture page";
        d["字体数: {0}"] = "Font count: {0}";
        d["字符表已导出 chars_*.txt"] = "Character table exported to chars_*.txt";
        d["审计: {0}  代码对象 {1}"] = "Audit: {0}  code objects {1}";
        d["平行时间线必须写成 ~Chapter:N:名字"] = "A parallel timeline must be written as ~Chapter:N:name";
        d["批量转换完成: {0} 成功, {1} 失败"] = "Batch conversion complete: {0} succeeded, {1} failed";
        d["找不到字体文件: "] = "Font file not found: ";
        d["样张: {0}  {1}x{2}"] = "Sample: {0}  {1}x{2}";
        d["样本对象 {0} 的指令字段："] = "Instruction fields of sample object {0}:";
        d["没有渲染出任何字形（字体可能不支持这些字符）"] = "No glyphs were rendered (the font may not support these characters)";
        d["源 data.win 里没有字体"] = "No fonts in the source data.win";
        d["源纹理页 {0}x{1} 超过 {2} 上限，无法原样搬运"] = "Source texture page {0}x{1} exceeds the {2} limit and cannot be moved as-is";
        d["（#{0}）"] = " (#{0})";
        d["（@"] = " (@";
        d["（必须先有 ~Chapter:"] = " (you must first have ~Chapter:";
        d["（无模板，按现有内容处理）"] = " (no template; using the existing content as-is)";
        d["（期望 Chapter:N:name 或 ~Chapter:N:name）"] = " (expected Chapter:N:name or ~Chapter:N:name)";
        d["）"] = ")";
        d["；若只想改官方章节请写成 Chapter:"] = "; to modify an official chapter only, write Chapter:";
        d["文案空值"] = "empty text";
        d["键 '{0}' 的 {1} 译文为空"] = "key '{0}': the {1} translation is empty";
        d["文案缺一侧"] = "missing one side";
        d["键 '{0}' 只有 {1} 一侧，另一种语言会显示键名本身"] = "key '{0}' exists only in {1}; the other language will display the key name itself";
        d["占位符不一致"] = "placeholder mismatch";
        d["键 '{0}'：{1} 用 [{2}] 而另一种语言用 [{3}]"] = "key '{0}': {1} uses [{2}] while the other language uses [{3}]";
        d["文案硬编码"] = "hard-coded text";
        d["控制台输出里有硬编码中文 \"{0}\"。\n"] = "hard-coded Chinese in console output: \"{0}\".\n";
        d["        → 用户可见文本必须走文案表：ntl_console_log(ntl_ts(\"键名\", [参数]));\n"] = "        → user-visible text must go through the text table: ntl_console_log(ntl_ts(\"KEY\", [args]));\n";
        d["        → 词条加在 api/ntl_i18n_out.gml（zh 原文 + en 译文）；故意中英并排则加标记 {0}"] = "        → add the entry to api/ntl_i18n_out.gml (zh original + en translation); if the pairing is intentional add marker {0}";
        d["词条缺失"] = "missing entry";
        d["引用了不存在的键 '{0}' —— ntl_t 会原样返回键名，界面会显示 \"{0}\""] = "references a key that does not exist: '{0}' — ntl_t returns the key as-is, so the UI shows \"{0}\"";
    }
}
