namespace Neutraled.Builder;

/// <summary>英文译文表（Deploy 组）。key = 中文原文（含 {0} 占位符），value = 英文。
/// 由 tools 脚本从 _i18n-builder/keys-deploy.json 生成，**不要手改单个条目**。</summary>
public static class LangTable_Deploy
{
    public static void Fill(Dictionary<string, string> d)
    {
        d["             %LOCALAPPDATA%\\DELTARUNE\\Neutraled\\dr-api.log   ← 章节选择器/根阶段"] = "             %LOCALAPPDATA%\\DELTARUNE\\Neutraled\\dr-api.log   ← chapter selector / root stage";
        d["           ……（还有更多，已省略）"] = "           ...(more items omitted)";
        d["           部署时 ByName() 会命中旧条目，改动静默不生效。"] = "           At deploy time ByName() hits the old entry, so the change silently has no effect.";
        d["           （Neutraled/templates 不存在 —— 安装包不完整？）"] = "           (Neutraled/templates does not exist -- is the package incomplete?)";
        d["         ntl-builder.exe --new-chapter \"我的第一个章节\""] = "         ntl-builder.exe --new-chapter 'My First Chapter'";
        d["         → 说明 RefCopy 是**新建条目**而不是**替换同名条目**；"] = "         → means RefCopy makes a **new entry** rather than **replacing the same-named entry**;";
        d["         先跑 ntl-builder.exe --new-chapter help 看可 fork 的清单，或见下面的列表"] = "         Run ntl-builder.exe --new-chapter help to see the forkable list, or see the list below";
        d["         先跑一次：ntl-builder.exe --deploy --chapter {0}   （它会自动备份原版）"] = "         Run this once: ntl-builder.exe --deploy --chapter {0}   (it backs up the original automatically)";
        d["         其它候选："] = "         Other candidates:";
        d["         可 fork 的 mod 章节目录："] = "         Forkable mod chapter directories:";
        d["         可用模板："] = "         Available templates:";
        d["         差异层只覆盖字节码 → 资源改动不会生效。若这些资源是 mod 的核心内容，"] = "         A diff layer only covers bytecode → resource changes will not take effect. If these resources are the core content of the mod,";
        d["         换个章节名字，或者加 --force 覆盖（会先删掉这个目录再重建）"] = "         rename the chapter, or add --force to overwrite (it deletes this directory first and rebuilds it)";
        d["         用法：--fork <mod目录名|mod id>[:作者[:chapterN]]"] = "         usage: --fork <mod directory name|mod id>[:author[:chapterN]]";
        d["         请把它作为**基底**（references.assets=inherit），或改用精灵/声音包重新打包。"] = "         Use it as the **base** (references.assets=inherit), or repackage it as a sprite/sound pack instead.";
        d["         （Mods.IsChapterFolder 的硬性要求；fork 时说明源 mod 的目录结构不标准）"] = "         (hard requirement of Mods.IsChapterFolder; when forking it means the source mod directory layout is non-standard)";
        d["      --slot N  --fork <mod>[:作者[:chapterN]]  --template room|empty  --force"] = "      --slot N  --fork <mod>[:author[:chapterN]]  --template room|empty  --force";
        d["      ntl-builder.exe --new-chapter help            看这份帮助"] = "      ntl-builder.exe --new-chapter help            show this help";
        d["    (无)"] = "    (none)";
        d["    ...已处理 {0}/{1}"] = "    ...processed {0}/{1}";
        d["    1) 把它作为该章的**基底**（Neutraled 里它就是合理的整包 mod）"] = "    1) Use it as the **base** for that chapter (in Neutraled it is a legitimate full-package mod)";
        d["    2) 一整包只允许一个 data.win 基底；其余 mod 用 scripts/ hooks/ 资源包/ files 覆盖来叠加"] = "    2) A full package allows only one data.win base; other mods stack on top via scripts/ hooks/ resource packs/ files overrides";
        d["    3) 确实要用它自己的资源池 → 用 --mod-force 强制生成（自担风险）"] = "    3) If you really need its own resource pool → use --mod-force to force generation (at your own risk)";
        d["    [冲突] {0} 已被前序 mod 复制，{1} 跳过（如需覆盖请声明 references.override）"] = "    [Conflict] {0} was already copied by an earlier mod, skipping {1} (declare references.override to overwrite)";
        d["    [无法表达] {0} 个新增对象（非 gml_Script_*，patch/gml 都覆盖不到，见报告）"] = "    [Unrepresentable] {0} newly added objects (not gml_Script_*, neither patch nor gml can cover them, see report)";
        d["    [真改动] {0}（{1} 字符）"] = "    [Real change] {0} ({1} chars)";
        d["    [警告] find_replace 目标不存在: {0}"] = "    [Warning] find_replace target does not exist: {0}";
        d["    [警告] patch 文件缺失: {0}"] = "    [Warning] patch file missing: {0}";
        d["    [警告] patch 目标不存在: {0}"] = "    [Warning] patch target does not exist: {0}";
        d["    [警告] {0} 声明了 codes 但缺少 references.source"] = "    [Warning] {0} declares codes but is missing references.source";
        d["    [警告] 引用源缺失: {0}"] = "    [Warning] reference source missing: {0}";
        d["    [警告] 找不到对象事件: {0}"] = "    [Warning] object event not found: {0}";
        d["    [警告] 脚本名冲突 {0} -> {1}"] = "    [Warning] script name conflict {0} -> {1}";
        d["    [跳过] {0} 不存在"] = "    [Skip] {0} does not exist";
        d["    [跳过] {0}: {1} (patch_skip)"] = "    [Skip] {0}: {1} (patch_skip)";
        d["    [跳过] {0}: {1} 不存在"] = "    [Skip] {0}: {1} does not exist";
        d["    gml/      {0} 个 .gml（作为新脚本导入）"] = "    gml/      {0} .gml files (imported as new scripts)";
        d["    patches/  {0} 个 .gml（覆盖已存在对象）"] = "    patches/  {0} .gml files (override existing objects)";
        d["    {0}[{1}] 基线: Kind={2} RefType={3} Type1={4} Type2={5} TypeInst={6} I={7} S={8} | 修改: Kind={9} RefType={10} Type1={11} Type2={12} TypeInst={13} I={14} S={15}"] = "    {0}[{1}] baseline: Kind={2} RefType={3} Type1={4} Type2={5} TypeInst={6} I={7} S={8} | modified: Kind={9} RefType={10} Type1={11} Type2={12} TypeInst={13} I={14} S={15}";
        d["    全角字距补偿: 已启用（检测到宽字形字体包）"] = "    Full-width spacing compensation: enabled (wide-glyph font pack detected)";
        d["    全角字距补偿: 未启用（无宽字形字体包）"] = "    Full-width spacing compensation: disabled (no wide-glyph font pack)";
        d["    内置字体包: {0} 个（中文等）"] = "    Built-in font packs: {0} (Chinese, etc.)";
        d["    写入 data.win 被占用，重试 {0}/{1}…（{2}: {3}）"] = "    data.win is locked while writing, retrying {0}/{1}... ({2}: {3})";
        d["    包装: {0}"] = "    Wrapping: {0}";
        d["    受影响指令示例（索引位移）:"] = "    Affected instruction samples (index shift):";
        d["    增强: {0}"] = "    Enhanced: {0}";
        d["    字符串 {0}→{1} / 函数 {2}→{3} / 变量 {4}→{5} / 对象 {6}→{7}"] = "    Strings {0}→{1} / Functions {2}→{3} / Variables {4}→{5} / Objects {6}→{7}";
        d["    对象事件 Hook 应用: {0} 个"] = "    Object event Hook applied: {0}";
        d["    对象事件: {0}.{1} ({2})"] = "    Object event: {0}.{1} ({2})";
        d["    把这种对象抽成「差异层」，会把**错误的资源索引**写进基底 → 功能静默错乱。"] = "    Extracting such objects into a 'diff layer' writes **wrong resource indexes** into the base → features break silently.";
        d["    改动 {0}  新增 {1}  删除 {2}"] = "    Changed {0}  Added {1}  Deleted {2}";
        d["    调用重定向: {0} 处（{1} 个代码块）"] = "    Call redirections: {0} ({1} code blocks)";
        d["    输入扫描: 命中缓存（{0} 个对象，基底 {1}）"] = "    Input scan: cache hit ({0} objects, base {1})";
        d["    输入扫描: 已缓存 {0} 个对象（键 {1}）"] = "    Input scan: cached {0} objects (key {1})";
        d["    音频防泄漏: {0}"] = "    Audio leak guard: {0}";
        d["   （Neutraled/templates 不存在 —— 安装包不完整？）"] = "   (Neutraled/templates does not exist -- is the package incomplete?)";
        d["  --- 前 12 个改动对象的语义差异 ---"] = "  --- semantic diff of the first 12 changed objects ---";
        d["  --- 差异指令明细（Kind / ReferenceType / 值）---"] = "  --- diff instruction details (Kind / ReferenceType / value) ---";
        d["  --- 问题明细（前 10）---"] = "  --- problem details (first 10) ---";
        d["  1) ntl-builder.exe --deploy --chapter root --force           生成章节产物（平行时间线会自动一起生成）"] = "  1) ntl-builder.exe --deploy --chapter root --force           generate the chapter output (parallel timelines are generated along with it)";
        d["  1) ntl-builder.exe --deploy --chapter {0} --force     把 mod 叠加进官方第 {1} 章"] = "  1) ntl-builder.exe --deploy --chapter {0} --force     overlay the mod onto official chapter {1}";
        d["  2) 启动 DELTARUNE（Steam）→ 章节选择器里翻到你的章节"] = "  2) Launch DELTARUNE (via Steam) → page to your chapter in the chapter selector";
        d["  2) 启动 DELTARUNE（Steam），进第 {0} 章看效果"] = "  2) Launch DELTARUNE (via Steam) and enter chapter {0} to see the result";
        d["  JSON 报告: "] = "  JSON report: ";
        d["  [dry-run] 不写盘"] = "  [dry-run] not writing to disk";
        d["  [fork] 原 chapters 声明 "] = "  [fork] original chapters declaration ";
        d["  [fork] 复制源 mod 的 data/ 目录（基底 data.win 等）"] = "  [fork] copying the source mod data/ directory (base data.win etc.)";
        d["  [fork] 源章节：{0}（id={1}，chapter={2}）"] = "  [fork] source chapter: {0} (id={1}, chapter={2})";
        d["  [写] "] = "  [write] ";
        d["  [写] {0}"] = "  [write] {0}";
        d["  [写] {0}（{1}x{2}）"] = "  [write] {0} ({1}x{2})";
        d["  [写] {0}（{1}，{2:F1} MB）"] = "  [write] {0} ({1}, {2:F1} MB)";
        d["  [失败] (a) 重新打开产物 data.win —— 产物不存在（"] = "  [Failed] (a) reopening the output data.win -- the output does not exist (";
        d["  [失败] 自检本身抛异常 —— "] = "  [Failed] the self-check itself threw an exception -- ";
        d["  [拒绝生成] 该包在打包时**重建了资源池**，字节码里的资源索引不可移植："] = "  [Refused] this package **rebuilt the resource pool** when packing, so resource indexes in the bytecode are not portable:";
        d["  [提示] 「{0}」匹配到 {1} 个，取第一个：{2}"] = "  [Tip] '{0}' matched {1} entries, taking the first: {2}";
        d["  [提示] 未找到 scr_input_manager，控制台输入屏蔽跳过"] = "  [Tip] scr_input_manager not found, skipping console input blocking";
        d["  [提示] 耗时大头是重新打开产物 data.win（"] = "  [Tip] most of the time is spent reopening the output data.win (";
        d["  [注意] {0} 个对象反编译失败，改动不会生效（见报告）"] = "  [Note] {0} objects failed to decompile; their changes will not take effect (see report)";
        d["  [目录] {0}"] = "  [Dir] {0}";
        d["  [结论] RefCopy 在本批样本上**保真**：跨资源池复制后语义一致"] = "  [Conclusion] RefCopy is **faithful** on this sample batch: semantics match after copying across resource pools";
        d["  [结论] 存在有损复制，需要针对上面这些对象补索引重映射"] = "  [Conclusion] lossy copies exist; index remapping is needed for the objects above";
        d["  [覆盖] 先删除已存在的目录：{0}"] = "  [Overwrite] deleting the existing directory first: {0}";
        d["  [警告] hook 包装失败: {0}"] = "  [Warning] hook wrapping failed: {0}";
        d["  [警告] {0} 个对象在修改版中不存在，差异层无法表达删除（前 5: {1}）"] = "  [Warning] {0} objects do not exist in the modified build; a diff layer cannot express deletions (first 5: {1})";
        d["  [警告] 候选超过上限 {0}，只处理前 {1} 个（其余见报告）"] = "  [Warning] candidates exceed the limit {0}; only the first {1} are processed (see report for the rest)";
        d["  [警告] 内置函数 Hook 失败: {0}"] = "  [Warning] built-in function Hook failed: {0}";
        d["  [警告] 写 JSON 报告失败: "] = "  [Warning] failed to write the JSON report: ";
        d["  [警告] 创建快捷方式失败: {0}"] = "  [Warning] failed to create the shortcut: {0}";
        d["  [警告] 原始代码替换失败: {0}"] = "  [Warning] raw code replacement failed: {0}";
        d["  [警告] 复制 {0} 出错: {1}"] = "  [Warning] error copying {0}: {1}";
        d["  [警告] 对象事件 Hook 失败: {0}"] = "  [Warning] object event Hook failed: {0}";
        d["  [警告] 找不到 ntl-gui.exe，跳过快捷方式（GUI 需要先构建 gui 项目）"] = "  [Warning] ntl-gui.exe not found, skipping the shortcut (GUI requires building the gui project first)";
        d["  [警告] 模板 {0} 里还有没替换的占位符 {1}（模板比脚手架新？）"] = "  [Warning] template {0} still has unreplaced placeholders {1} (is the template newer than the scaffold?)";
        d["  [警告] 没找到 {0} 的官方原版备份，退而用当前 data.win"] = "  [Warning] no official backup found for {0}, falling back to the current data.win";
        d["  [警告] 源 mod 是外部引擎章节（kristal_external），fork 后成了普通时间线章节；要保留外部启动请手动改回"] = "  [Warning] the source mod is an external engine chapter (kristal_external); after forking it becomes a normal timeline chapter. To keep the external launch, change it back manually";
        d["  [警告] 源 mod.json 解析失败（"] = "  [Warning] failed to parse the source mod.json (";
        d["  [警告] 源反编译失败 {0}: {1}"] = "  [Warning] source decompile failed {0}: {1}";
        d["  [警告] 该 mod 改动了资源表（精灵/声音/房间/字体）。"] = "  [Warning] this mod changed the resource tables (sprites/sounds/rooms/fonts).";
        d["  [警告] 还原失败 {0}: {1}"] = "  [Warning] restore failed {0}: {1}";
        d["  [跳过] 已有基底数据：{0}（想换就手动删掉它再跑一次）"] = "  [Skip] base data already exists: {0} (to change it, delete it manually and run again)";
        d["  [重要] 出现同名重复代码条目 {0} 个（{1} 个样本经新条目才保真）"] = "  [Important] {0} duplicate code entries with the same name appeared ({1} samples are only faithful through the new entry)";
        d["  [错误] --mode fork 需要 --fork <mod目录名|mod id>[:作者[:chapterN]]"] = "  [Error] --mode fork requires --fork <mod directory name|mod id>[:author[:chapterN]]";
        d["  [错误] --mode 只支持 independent / overlay / fork（收到 '{0}'）"] = "  [Error] --mode only supports independent / overlay / fork (received '{0}')";
        d["  [错误] --new-chapter 需要一个章节名字，例如："] = "  [Error] --new-chapter needs a chapter name, for example:";
        d["  [错误] mod 的叶子目录名必须是 \"root\" 或以 \"chapter\" 开头且长度 > 7，当前是 \"{0}\""] = "  [Error] a mod leaf directory name must be 'root' or start with 'chapter' and be longer than 7 characters; currently '{0}'";
        d["  [错误] 作者名不能包含 {0}（它会当作目录名）"] = "  [Error] the author name must not contain {0} (it is used as a directory name)";
        d["  [错误] 扫描 mods 失败："] = "  [Error] failed to scan mods: ";
        d["  [错误] 找不到 {0} 的 data.win（备份目录和游戏目录都没有）"] = "  [Error] no data.win found for {0} (neither in the backup directory nor in the game directory)";
        d["  [错误] 找不到模板目录：{0}"] = "  [Error] template directory not found: {0}";
        d["  [错误] 找不到要 fork 的 mod：「{0}」"] = "  [Error] no mod to fork found: '{0}'";
        d["  [错误] 目录已存在：{0}"] = "  [Error] directory already exists: {0}";
        d["  [错误] 章节名字不能包含 {0}（它会当作 mod 目录名）"] = "  [Error] the chapter name must not contain {0} (it is used as a mod directory name)";
        d["  [错误] 编译失败:"] = "  [Error] compile failed:";
        d["  [错误] 编译失败（阶段2）:"] = "  [Error] compile failed (stage 2):";
        d["  api 脚本: {0} 个"] = "  api scripts: {0}";
        d["  fork 自  : {0}"] = "  fork from: {0}";
        d["  mod patches: {0} 覆盖 / {1} 局部替换 / {2} 跳过"] = "  mod patches: {0} overridden / {1} locally replaced / {2} skipped";
        d["  mod 目录 : {0}"] = "  mod dir  : {0}";
        d["  mod 脚本: {0} 个（入口: {1}）"] = "  mod scripts: {0} (entry: {1})";
        d["  references.codes: {0} 个{1}"] = "  references.codes: {0}{1}";
        d["  ✅ 安装完成"] = "  ✅ Install complete";
        d["  ✅ 已还原 {0} 个 data.win，Neutraled 产物已清理"] = "  ✅ Restored {0} data.win files, Neutraled output cleaned up";
        d["  下一步：双击桌面上的 {0} 选择章节与 mod，然后点「部署并启动」"] = "  Next: double-click {0} on the desktop, pick a chapter and a mod, then click 'Deploy and Launch'";
        d["  下一步：本包不含图形界面 —— 运行 {0} 打开网页界面，或运行 {1} 直接部署并启动"] = "  Next: this package has no GUI -- run {0} for the web UI, or {1} to deploy and launch";
        d["  事件代码: {0} 个"] = "  Event code entries: {0}";
        d["  事件绑定 {0}({1})"] = "  Event binding {0}({1})";
        d["  产物: "] = "  Output: ";
        d["  代码对象: 基线 {0} / 修改版 {1}"] = "  Code objects: baseline {0} / modified {1}";
        d["  体积: "] = "  Size: ";
        d["  修改版: "] = "  Modified: ";
        d["  内置函数 Hook 声明: {0} 条（涉及 {1} 个函数）"] = "  Built-in function Hook declarations: {0} (covering {1} functions)";
        d["  函数 hook 声明: {0} 条"] = "  Function hook declarations: {0}";
        d["  判定: "] = "  Verdict: ";
        d["  判据: 需要渲染的字符中，能被字体画出的比例（>= "] = "  Criterion: of the characters that need rendering, the share the font can draw (>= ";
        d["  原始代码替换: {0} 个"] = "  Raw code replacements: {0}";
        d["  原版备份: {0} 个 data.win → {1}（同时在 {2} 留一份）"] = "  Original backups: {0} data.win → {1} (a copy is also left in {2})";
        d["  基底数据 : {0} ← 官方 {1}"] = "  base data: {0} ← official {1}";
        d["  基线: "] = "  Baseline: ";
        d["  声音资源包: {0}"] = "  Sound resource pack: {0}";
        d["  字体资源包: {0}"] = "  Font resource pack: {0}";
        d["  对象 {0} 创建"] = "  Object {0} created";
        d["  对象事件 Hook 声明: {0} 条"] = "  Object event Hook declarations: {0}";
        d["  层: {0} / {1} / {2}  id={3}"] = "  Layer: {0} / {1} / {2}  id={3}";
        d["  已复制 {0} 个对象"] = "  Copied {0} objects";
        d["  已复制 {0} 个目录"] = "  Copied {0} directories";
        d["  安装器已装到 {0}"] = "  Installer placed at {0}";
        d["  [警告] --src 目录里没有 api/ 与 docs/，忽略: {0}"] = "  [warn] --src directory has no api/ and docs/: ignored {0}";
        d["  已移除快捷方式: {0}"] = "  Removed shortcut: {0}";
        d["  已还原: {0}"] = "  Restored: {0}";
        d["  引导注入 -> {0}"] = "  Boot injection -> {0}";
        d["  引导目标: "] = "  Boot target: ";
        d["  引用复制: {0} <- {1}（{2} 个代码对象）"] = "  RefCopy: {0} <- {1} ({2} code objects)";
        d["  快捷方式: {0}"] = "  Shortcut: {0}";
        d["  房间地图 : Neutraled/kristal-maps/{0}.png + .map.json"] = "  Room map  : Neutraled/kristal-maps/{0}.png + .map.json";
        d["  执行 RefCopy..."] = "  Running RefCopy...";
        d["  指令级候选: 改动 {0} + 新增 {1} = {2}（另排除 {3} 个纯元数据差异）"] = "  Instruction-level candidates: changed {0} + added {1} = {2} (excluding {3} metadata-only diffs)";
        d["  控制台输入屏蔽: {0}"] = "  Console input blocking: {0}";
        d["  教程：Neutraled/docs/CHAPTER_DEV.md"] = "  Tutorial: Neutraled/docs/CHAPTER_DEV.md";
        d["  文本来源: "] = "  Text source: ";
        d["  日志     : %LOCALAPPDATA%\\DRTL<顺序号>_<短码>\\Neutraled\\dr-api.log   ← 章节进程（= 本 mod 的存档目录）"] = "  Log      : %LOCALAPPDATA%\\DRTL<order>_<short code>\\Neutraled\\dr-api.log   ← chapter process (= this mod's save directory)";
        d["  样本: {0} 个对象（max={1}）"] = "  Sample: {0} objects (max={1})";
        d["  检查目标: "] = "  Check target: ";
        d["  正确做法（按推荐顺序）:"] = "  Correct approach (in recommended order):";
        d["  池: 字符串 {0}→{1}  函数 {2}→{3}  变量 {4}→{5}  对象 {6}→{7}"] = "  Pool: Strings {0}→{1}  Functions {2}→{3}  Variables {4}→{5}  Objects {6}→{7}";
        d["  注入完成"] = "  Injection complete";
        d["  渲染不出来的样例（"] = "  Samples that cannot be rendered (";
        d["  游戏目录: {0}"] = "  Game dir: {0}";
        d["  源:   "] = "  src:   ";
        d["  源与目标相同（开发环境），跳过文件复制"] = "  Source and target are the same (development environment), skipping file copy";
        d["  源目录:   {0}"] = "  src dir: {0}";
        d["  源码级过滤: 真实改动 {0} / 索引噪声 {1} / 反编译失败 {2}"] = "  Source-level filter: real changes {0} / index noise {1} / decompile failures {2}";
        d["  目标: "] = "  dest: ";
        d["  目标:     {0}"] = "  dest:     {0}";
        d["  章节: "] = "  Chapter: ";
        d["  章节名   : {0}   （章节选择器里显示的就是它）"] = "  Chapter  : {0}   (this is what the chapter selector displays)";
        d["  精灵导入合计: {0}"] = "  Sprite imports total: {0}";
        d["  精灵资源包: {0}"] = "  Sprite resource pack: {0}";
        d["  结果: 保真 {0} / 不一致 {1} / 失败 {2}   （共 {3}）"] = "  Result: faithful {0} / mismatched {1} / failed {2}   (of {3})";
        d["  编译成功"] = "  Compile succeeded";
        d["  自动检测到: {0}"] = "  Auto-detected: {0}";
        d["  说明: 该层可叠加在任意基底之上；若与其它层改同一对象，部署时会报冲突（功能冲突，需人工裁决）"] = "  Note: this layer can be stacked on any base; if it changes the same object as another layer, deploy reports a conflict (a functional conflict that needs a manual decision)";
        d["  资源:"] = "  Resources:";
        d["  输入函数重定向: {0} 处（涉及 {1} 个代码块，字节码预筛跳过 {2} 个）"] = "  Input function redirections: {0} ({1} code blocks involved, {2} skipped by bytecode pre-filter)";
        d["  需要渲染: "] = "  Needs rendering: ";
        d["  顺序号   : {0}     （章节选择器里的位置；改 mod.json 的 order 就能改）"] = "  Slot     : {0}     (position in the chapter selector; change order in mod.json to move it)";
        d["  （Neutraled/ 目录本身与你的 mods/存档 都保留了，如需彻底删除请手动移除）"] = "  (the Neutraled/ directory itself and your mods/saves are kept; remove them manually if you want them gone)";
        d["  （另有 {0} 个候选，可用 --game 指定）"] = "  ({0} more candidates; use --game to specify)";
        d[" MB   修改时间: "] = " MB   Modified: ";
        d[" ms）"] = " ms)";
        d[" ms，229MB 的 data.win 解析本身就要数秒），其余检查合计 "] = " ms; parsing a 229MB data.win alone takes seconds), the remaining checks take ";
        d[" ms；产物只 Load 一次。"] = " ms; the output is loaded only once.";
        d[" → 替换成新的时间线条目（order "] = " → replaced with a new timeline entry (order ";
        d[" 个字符（其中 CJK "] = " chars (of which CJK ";
        d[" 个目标）"] = " targets)";
        d[" 个警告（"] = " warnings (";
        d[" 警告）"] = " warning)";
        d[" 通过 / >= "] = " pass / >= ";
        d[" 项"] = " items";
        d[" 项，用时 "] = " items, elapsed ";
        d["(无)"] = "(none)";
        d["===== Neutraled 卸载/还原 ====="] = "===== Neutraled uninstall / restore =====";
        d["===== Neutraled 安装器 ====="] = "===== Neutraled installer =====";
        d["===== RefCopy 保真度验证 ====="] = "===== RefCopy fidelity verification =====";
        d["===== 内容级自检（语言文本 × 字体字形）====="] = "===== Content-level self-check (language text x font glyphs) =====";
        d["===== 差异层提取（整包 mod → 可叠加层） ====="] = "===== Diff layer extraction (full-package mod → stackable layer) =====";
        d["===== 源码级差异层提取（--layer-from-base）====="] = "===== Source-level diff layer extraction (--layer-from-base) =====";
        d["===== 章节已生成 ====="] = "===== Chapter generated =====";
        d["===== 部署后自检 ["] = "===== Post-deploy self-check [";
        d["Neutraled 引导注入编译失败"] = "Neutraled boot injection compile failed";
        d["Neutraled 核心编译失败"] = "Neutraled core compile failed";
        d["[结论] 相对基线没有真实语义改动（差异全是索引位移噪声），无需生成层"] = "[Conclusion] no real semantic changes relative to the baseline (all differences are index-shift noise), no layer needed";
        d["[错误] 找不到: "] = "[Error] not found: ";
        d["[错误] 找不到源: "] = "[Error] source not found: ";
        d["[错误] 找不到目标: "] = "[Error] target not found: ";
        d["[错误] 无法推断章节，请用 --chapter chapterN"] = "[Error] cannot infer the chapter, use --chapter chapterN";
        d["[错误] 无法推断章节，请用 --chapter chapterN 指定"] = "[Error] cannot infer the chapter, specify it with --chapter chapterN";
        d["[错误] 没找到 DELTARUNE 安装目录，请用 --game <目录> 指定"] = "[Error] DELTARUNE install directory not found, specify it with --game <dir>";
        d["[错误] 没找到游戏目录，请用 --game <目录> 指定"] = "[Error] game directory not found, specify it with --game <dir>";
        d["[错误] 没有共同代码对象"] = "[Error] no common code objects";
        d["[错误] 没有找到备份目录（Neutraled/backup），无法安全还原"] = "[Error] backup directory not found (Neutraled/backup), cannot restore safely";
        d["[错误] 目录内没有 data.win: "] = "[Error] no data.win in the directory: ";
        d["[错误] 相对基线没有任何字节码差异，无法生成差异层"] = "[Error] no bytecode differences relative to the baseline, cannot generate a diff layer";
        d["[错误] 缺少官方基线: "] = "[Error] missing official baseline: ";
        d["[错误] 该目录没有 DELTARUNE.exe: {0}"] = "[Error] that directory has no DELTARUNE.exe: {0}";
        d["] 失败: "] = "] failed: ";
        d["] 跳过 —— "] = "] skipped -- ";
        d["] 跳过 —— 产物不存在: "] = "] skipped -- output does not exist: ";
        d["下一步（一条一条复制执行）："] = "Next (copy and run one line at a time):";
        d["全部通过（"] = "All passed (";
        d["发现严重问题（失败 "] = "Found serious problems (failed ";
        d["可 fork 的现成章节（--fork 后面写 <mod目录名>[:作者[:chapterN]]）："] = "Ready-made forkable chapters (write <mod directory name>[:author[:chapterN]] after --fork):";
        d["可用模板（"] = "Available templates (";
        d["失败"] = "FAIL";
        d["找不到代码条目: "] = "Code entry not found: ";
        d["找不到引导目标代码条目: {0}"] = "Boot target code entry not found: {0}";
        d["用法：ntl-builder.exe --new-chapter <章节名字> [选项]"] = "usage: ntl-builder.exe --new-chapter <chapter name> [options]";
        d["结果: "] = "Result: ";
        d["结果: 全部通过（用时 "] = "Result: all passed (elapsed ";
        d["结果: 发现严重问题（失败 "] = "Result: found serious problems (failed ";
        d["结果: 发现严重问题（失败 1 项 + 未能执行 b/c/d，用时 "] = "Result: found serious problems (1 item failed + could not run b/c/d, elapsed ";
        d["选项：--author <作者>  --mode independent|overlay|fork  --chapter chapterN"] = "Options: --author <author>  --mode independent|overlay|fork  --chapter chapterN";
        d["通过"] = "PASS";
        d["通过但含 "] = "Passed with ";
        d["）"] = ")";
        d["）: "] = "): ";
        d["），按空对象重建"] = "), rebuilding as an empty object";
        d["），自检无法继续"] = "), the self-check cannot continue";
        d["）："] = "):";
        d["，警告 "] = ", warnings ";
    }
}
