namespace Neutraled.Builder;

/// <summary>英文译文表（Mods 组）。key = 中文原文（含 {0} 占位符），value = 英文。
/// 由 tools 脚本从 _i18n-builder/keys-mods.json 生成，**不要手改单个条目**。</summary>
public static class LangTable_Mods
{
    public static void Fill(Dictionary<string, string> d)
    {
        d["          已按 root 目标安装 —— 章节 mod 请把包改名成 <名字>-chapterN.ntlmod，"] = "          Installed for the root target — for a chapter mod, rename the package to <name>-chapterN.ntlmod,";
        d["          或在 mod.json 里加 \"chapter\": \"chapterN\"，否则它不会进入对应章节产物。"] = "          or add \"chapter\": \"chapterN\" to mod.json, otherwise it will not enter the matching chapter product.";
        d["         → --mod-force：仍按官方备份尝试"] = "         → --mod-force: try against the official backup anyway";
        d["         → 放一份 Kristal 到 <游戏根>\\Kristal-main，把 love.exe 放进 <游戏根>\\Kristal-main\\ 或 Neutraled\\tools\\love\\"] = "         → put a copy of Kristal at <game root>\\Kristal-main and love.exe into <game root>\\Kristal-main\\ or Neutraled\\tools\\love\\";
        d["         → 跳过该章（补丁基于其它游戏版本）；确认无误可用 --mod-force 强制尝试"] = "         → skipping this chapter (the patch is based on another game version); if you are sure it is fine, use --mod-force to force it";
        d["         期望 {0} = {1}…"] = "         expected {0} = {1}...";
        d["         本机 {0} = {1}…"] = "         local {0} = {1}...";
        d["        Neutraled 导入器只处理成品 data.win / xdelta 补丁（不内嵌 C# 运行时）。"] = "        The Neutraled importer only handles a finished data.win / xdelta patch (it does not embed a C# runtime).";
        d["       1) 放进某个 Kristal 项目的 mods/ 目录，然后对**那个项目**跑 --import-kristal"] = "       1) put it into the mods/ directory of some Kristal project, then run --import-kristal on **that project**";
        d["       2) 想做成 Neutraled 独立章节，需要项目级 data.win（Kristal 主引擎尚未移植）"] = "       2) to make it a standalone Neutraled chapter you need a project-level data.win (the Kristal main engine has not been ported yet)";
        d["      多个插件提供同名资源时，后到者被丢弃；若顺序不对，请调整命令行里的插件先后顺序。"] = "      When several plugins provide a resource with the same name, the later one is dropped; if the order is wrong, adjust the plugin order on the command line.";
        d["      期望结构: {0}\\scripts\\*.lua  或  {1}\\assets\\sprites|sounds\\"] = "      Expected structure: {0}\\scripts\\*.lua  or  {1}\\assets\\sprites|sounds\\";
        d["      若这是无意的，请修正路径后重跑；本次仍会继续转换已合并的插件。"] = "      If this was not intended, fix the path and rerun; this run will still convert the plugins already merged.";
        d["      请把 --import-kristal-merge 的参数直接指向其中某一个目录。"] = "      Point the --import-kristal-merge argument directly at one of those directories.";
        d["     可行路径："] = "     Possible routes:";
        d["     它必须挂在某个 Kristal 项目下运行（项目的 mod.json 决定 chapter/map/party）。"] = "     It must run under some Kristal project (the project mod.json decides chapter/map/party).";
        d["     暂存目录已清理。"] = "     Staging directory cleaned up.";
        d["     条目数 {0} → {1}"] = "     Entry count {0} → {1}";
        d["     现场保留: {0}"] = "     Kept for inspection: {0}";
        d["     用法: --import-kristal-merge <宿主项目目录> <插件目录1> [插件目录2 ...]"] = "     Usage: --import-kristal-merge <host project dir> <plugin dir 1> [plugin dir 2 ...]";
        d["     该目录既没有 mod.json，也没有 scripts/ 或 assets/，请确认路径。"] = "     This directory has neither mod.json nor scripts/ or assets/; check the path.";
        d["     请按上面的 [失败]/[跳过] 提示修正插件路径后重试。"] = "     Fix the plugin paths following the [Failed]/[Skip] notes above, then retry.";
        d["     请确认路径；Kristal 项目目录里应当能看到 mod.json / assets / scripts。"] = "     Check the path; a Kristal project directory should show mod.json / assets / scripts.";
        d["     这个目录只有 scripts/ 或 assets/ —— 它本身就是插件型 mod，不能当宿主。请改传含 mod.json 的项目目录。"] = "     This directory only has scripts/ or assets/ — it is itself a plugin-type mod and cannot be a host. Pass a project directory that contains mod.json instead.";
        d["     这类包无法作为普通 mod 转换，将注册为**外部引擎章节**（照样出现在 mods/ 与章节选择器里）"] = "     Such packages cannot be converted as an ordinary mod; they will be registered as an **external engine chapter** (still shown in mods/ and the chapter selector)";
        d["     验证: {0} → {1}"] = "     Verify: {0} → {1}";
        d["    1) 用 UTMT 打开 chapterN_windows/data.win，运行该 .csx，另存为 new.win"] = "    1) open chapterN_windows/data.win with UTMT, run that .csx, and save as new.win";
        d["    1) 编辑 main.lua（随便改一行 print）"] = "    1) edit main.lua (change any print line)";
        d["    2) 关闭游戏后运行 Neutraled\\launch.ps1"] = "    2) close the game, then run Neutraled\\launch.ps1";
        d["    3) 看日志里的 ["] = "    3) look in the log for [";
        d["    README.md      使用说明"] = "    README.md      usage notes";
        d["    [{0}] 读取 {1}: {2}"] = "    [{0}] read {1}: {2}";
        d["    [下钻] 真正的插件根: {0}"] = "    [Drill-down] real plugin root: {0}";
        d["    [失败] 该目录下有 {0} 个候选插件，无法自动判断用哪个："] = "    [Failed] this directory has {0} candidate plugins; cannot tell which one to use:";
        d["    [失败] 该目录（含 {0} 层子目录）既没有 scripts/ 也没有 assets/，请确认路径。"] = "    [Failed] this directory (including {0} levels of subdirectories) has neither scripts/ nor assets/; check the path.";
        d["    [提示] 基线有 {0} 个声音无内嵌数据（不参与差分）"] = "    [Tip] the baseline has {0} sounds without embedded data (not part of the diff)";
        d["    [警告] {0} 帧 BoundingWidth/Height != 源尺寸（包围盒与帧不同），导入器 schema 不表达，往返会丢失"] = "    [Warning] {0} frames have BoundingWidth/Height != source size (bounding box differs from the frame); the importer schema cannot express it, so a round trip loses it";
        d["    [警告] {0} 帧 TargetWidth/Height != SourceWidth/Height（缩放帧），导入器 schema 不表达该缩放，往返会丢失"] = "    [Warning] {0} frames have TargetWidth/Height != SourceWidth/Height (scaled frames); the importer schema cannot express that scale, so a round trip loses it";
        d["    [警告] {0} 帧 {1}: 无 TexturePageItem -> 写 1x1 占位图"] = "    [Warning] {0} frame {1}: no TexturePageItem -> writing a 1x1 placeholder";
        d["    [警告] {0}: {1} 无纹理页"] = "    [Warning] {0}: {1} has no texture page";
        d["    [警告] {0}: {1} 源尺寸为 0 ({2}x{3}) -> 写 1x1 占位图"] = "    [Warning] {0}: {1} has source size 0 ({2}x{3}) -> writing a 1x1 placeholder";
        d["    [警告] {0}: {1} 纹理页 {2} 无像素数据"] = "    [Warning] {0}: {1} texture page {2} has no pixel data";
        d["    [警告] {0}: {1} 纹理页 {2} 标记为外部纹理(TextureExternal)"] = "    [Warning] {0}: {1} texture page {2} is marked as an external texture (TextureExternal)";
        d["    [警告] {0}: {1} 纹理页 {2} 解码失败 {3}: {4}"] = "    [Warning] {0}: {1} texture page {2} decode failed {3}: {4}";
        d["    [警告] {0}: {1} 裁切失败 {2}: {3}"] = "    [Warning] {0}: {1} crop failed {2}: {3}";
        d["    [警告] {0}: {1} 裁切越界 ({2},{3},{4}x{5}) 超出纹理页 {6}x{7} -> 写 1x1 占位图"] = "    [Warning] {0}: {1} crop out of bounds ({2},{3},{4}x{5}) exceeds texture page {6}x{7} -> writing a 1x1 placeholder";
        d["    [警告] {0}: 另有 {1} 条纹理页警告已折叠"] = "    [Warning] {0}: {1} more texture page warnings collapsed";
        d["    [警告] {0}: 纹理页 {1} RGBA 长度 {2} != {3}，跳过像素差分"] = "    [Warning] {0}: texture page {1} RGBA length {2} != {3}; skipping the pixel diff";
        d["    [警告] {0}: 纹理页 {1} 取像素失败 {2}，跳过像素差分"] = "    [Warning] {0}: texture page {1} pixel fetch failed {2}; skipping the pixel diff";
        d["    [警告] 写 PNG 失败 {0}"] = "    [Warning] writing PNG failed {0}";
        d["    [警告] 占位图写入失败 {0}: {1}"] = "    [Warning] writing the placeholder failed {0}: {1}";
        d["    [警告] 另有 {0} 条声音警告已折叠"] = "    [Warning] {0} more sound warnings collapsed";
        d["    [警告] 另有 {0} 条字体警告已折叠"] = "    [Warning] {0} more font warnings collapsed";
        d["    [警告] 另有 {0} 条精灵警告已折叠"] = "    [Warning] {0} more sprite warnings collapsed";
        d["    [警告] 基线有 {0} 个同名声音，取首个"] = "    [Warning] the baseline has {0} sounds with the same name; using the first";
        d["    [警告] 声音 {0} 无内嵌数据（外部/audiogroup，File={1}）-> 跳过"] = "    [Warning] sound {0} has no embedded data (external/audiogroup, File={1}) -> skipping";
        d["    [警告] 声音 {0} 音频魔数未知 '{1}'（原 Type='{2}'）-> 写 .bin，type 用原值"] = "    [Warning] sound {0} has an unknown audio magic '{1}' (original Type='{2}') -> writing .bin, keeping the original type";
        d["    [警告] 字体 {0} 写 PNG 失败 {1}"] = "    [Warning] font {0}: writing PNG failed {1}";
        d["    [警告] 字体 {0} 无纹理页 -> 跳过"] = "    [Warning] font {0} has no texture page -> skipping";
        d["    [警告] 字体 {0} 没有纹理页条目（结构无法表达）-> 跳过，保留基底原样"] = "    [Warning] font {0} has no texture page entry (the structure cannot express it) -> skipping, keeping the base as is";
        d["    [警告] 插件 mod.json 解析失败（{0}），改用目录名"] = "    [Warning] plugin mod.json parse failed ({0}); using the directory name instead";
        d["    [警告] 有 {0} 个同名字体，取首个"] = "    [Warning] there are {0} fonts with the same name; using the first";
        d["    [警告] 有 {0} 个同名精灵，取首个"] = "    [Warning] there are {0} sprites with the same name; using the first";
        d["    [警告] 精灵 {0} 有帧没有纹理页条目（结构无法表达）-> 跳过，保留基底原样"] = "    [Warning] sprite {0} has frames without a texture page entry (the structure cannot express it) -> skipping, keeping the base as is";
        d["    [警告] 精灵 {0} 类型 {1}（Spine/SWF/Vector），资源包 schema 不表达 -> 跳过"] = "    [Warning] sprite {0} has type {1} (Spine/SWF/Vector), which the resource pack schema cannot express -> skipping";
        d["    [警告] 跳过无名声音"] = "    [Warning] skipping an unnamed sound";
        d["    [警告] 跳过无名字体"] = "    [Warning] skipping an unnamed font";
        d["    [警告] 跳过无名精灵"] = "    [Warning] skipping an unnamed sprite";
        d["    hooks/         函数 Hook 示例"] = "    hooks/         function hook examples";
        d["    main.lua       入口脚本 ← 从这里开始改"] = "    main.lua       entry script ← start editing here";
        d["    mod.json       元数据（已填好，可直接用）"] = "    mod.json       metadata (already filled in, ready to use)";
        d["    on_frame.lua   每帧执行"] = "    on_frame.lua   runs every frame";
        d["    {0,-10} 基线 {1,4} MB  差异 {2,6:F2}%"] = "    {0,-10} baseline {1,4} MB  diff {2,6:F2}%";
        d["    {0,-24} {1,6} 次"] = "    {0,-24} {1,6} calls";
        d["    → 判定: {0}"] = "    → verdict: {0}";
        d["    → 差异过大，无法确定章节（请用 --chapter 指定）"] = "    → diff too large, cannot determine the chapter (use --chapter to specify)";
        d["    内容: scripts {0} 个（其中 .lua {1}）/ assets {2} 个 / 其它 {3} 个"] = "    Content: {0} scripts ({1} of them .lua) / {2} assets / {3} other";
        d["    合并为 mods/{0}/{1}"] = "    Merged into mods/{0}/{1}";
        d["    声音: 导出 {0} / 未变 {1} / 无数据 {2}"] = "    Sounds: exported {0} / unchanged {1} / no data {2}";
        d["    字体: 导出 {0} / 未变 {1} / 无字形或纹理 {2} / 坏字形 {3}"] = "    Fonts: exported {0} / unchanged {1} / no glyphs or texture {2} / bad glyphs {3}";
        d["    宿主: {0}"] = "    Host: {0}";
        d["    宿主文件: {0} 个"] = "    Host files: {0}";
        d["    暂存: {0}"] = "    Staging: {0}";
        d["    章节声明: {0}"] = "    Chapter declaration: {0}";
        d["    精灵: 导出 {0} / 未变 {1} / 0帧 {2} / 非普通类型 {3} / 坏帧 {4} / 无纹理跳过 {5}"] = "    Sprites: exported {0} / unchanged {1} / 0-frame {2} / non-normal type {3} / bad frames {4} / skipped no texture {5}";
        d["    资源: 精灵 {0} / 声音 {1} / 其它 {2}"] = "    Resources: sprites {0} / sounds {1} / other {2}";
        d["    资源上提: sprites {0} / sounds {1}"] = "    Resources hoisted: sprites {0} / sounds {1}";
        d["    转换报告: {0}"] = "    Conversion report: {0}";
        d["  + assets/fonts/ntl_cjk.ttf  ({0} 字节，中文字形)"] = "  + assets/fonts/ntl_cjk.ttf  ({0} bytes, Chinese glyphs)";
        d["  + src/ntlconsole.lua  ({0} 字节)"] = "  + src/ntlconsole.lua  ({0} bytes)";
        d["  + {0}  （热更新入口：改它即可，不必再注入）"] = "  + {0}  (hot-reload entry: just edit it, no need to inject again)";
        d["  + {0}/libraries/ntlconsole/lib.lua  ({1} 字节，冗余保险)"] = "  + {0}/libraries/ntlconsole/lib.lua  ({1} bytes, redundancy safety)";
        d["  = assets/fonts/ntl_cjk.ttf 已存在（沿用）"] = "  = assets/fonts/ntl_cjk.ttf already exists (kept)";
        d["  = main.lua 已挂过钩子（沿用）"] = "  = main.lua already has the hook (kept)";
        d["  API 使用统计（Top 12）:"] = "  API usage stats (Top 12):";
        d["  Kristal mod: {0} v{1}  基底章节 {2}  起始地图 {3}"] = "  Kristal mod: {0} v{1}  base chapter {2}  starting map {3}";
        d["  Kristal 宿主合并: {0}  v{1}  基底章节 {2}"] = "  Kristal host merge: {0}  v{1}  base chapter {2}";
        d["  [dry-run] {0} → ref/data.win（基线 {1}）"] = "  [dry-run] {0} → ref/data.win (baseline {1})";
        d["  [dry-run] 不写盘（去掉 --dry-run 即执行 Kristal 转换）"] = "  [dry-run] nothing written (drop --dry-run to run the Kristal conversion)";
        d["  [dry-run] 不写盘（去掉 --dry-run 即执行安装）"] = "  [dry-run] nothing written (drop --dry-run to run the install)";
        d["  [dry-run] 不写盘（去掉 --dry-run 即注册）"] = "  [dry-run] nothing written (drop --dry-run to register)";
        d["  [dry-run] 整包 data.win 复制 → ref/data.win（{0} MB）"] = "  [dry-run] whole-package data.win copied → ref/data.win ({0} MB)";
        d["  [冲突] {0} 处同名文件 —— 保留先到者，丢弃后到者（未静默覆盖）:"] = "  [Conflict] {0} files with the same name — keeping the first, dropping the later ones (no silent overwrite):";
        d["  [去重] {0} 已存在（{1}），跳过重复项"] = "  [Dedupe] {0} already exists ({1}); skipping the duplicate";
        d["  [外部章节] 已登记：选中该章节 → 退出游戏并启动 {0}（引擎 {1}）"] = "  [External chapter] registered: selecting this chapter → exits the game and launches {0} (engine {1})";
        d["  [打包 mod] {0} -> {1}"] = "  [Pack mod] {0} -> {1}";
        d["  [扫描] mods 清单命中磁盘缓存（{0} 个）"] = "  [Scan] mods manifest hit the disk cache ({0})";
        d["  [控制台] ⚠ 注入失败，照常启动（不影响玩）"] = "  [Console] ⚠ injection failed, starting normally (gameplay unaffected)";
        d["  [控制台] ✅ 完成 —— 进游戏后按 F2"] = "  [Console] ✅ done — press F2 in game";
        d["  [控制台] 已是最新（F2 打开）"] = "  [Console] already up to date (F2 to open)";
        d["  [控制台] 给外部引擎装配/更新 Neutraled 控制台 …"] = "  [Console] installing/updating the Neutraled console for the external engine ...";
        d["  [控制台] 跳过: "] = "  [Console] Skipped: ";
        d["  [提示] 没找到 Kristal 引擎或 LÖVE 运行时，无法登记为外部章节"] = "  [Tip] no Kristal engine or LÖVE runtime found; cannot register it as an external chapter";
        d["  [提示] 没有备份 {0}，无需还原"] = "  [Tip] no backup of {0}; nothing to restore";
        d["  [插件 {0}/{1}] {2}"] = "  [Plugin {0}/{1}] {2}";
        d["  [无法独立转换] 这是 Kristal **插件型 mod**（只有 scripts/ + assets/，没有 mod.json）"] = "  [Cannot convert standalone] this is a Kristal **plugin-type mod** (only scripts/ + assets/, no mod.json)";
        d["  [注意] 有 {0} 个插件未被合并 —— 转换产物将缺少它们的内容:"] = "  [Note] {0} plugins were not merged — the converted product will be missing their content:";
        d["  [警告] mod.json 解析失败: {0}: {1}"] = "  [Warning] mod.json parse failed: {0}: {1}";
        d["  [警告] xdelta 目标不是 data.win: "] = "  [Warning] xdelta target is not data.win: ";
        d["  [警告] {0} 解析失败: {1}"] = "  [Warning] failed to parse {0}: {1}";
        d["  [警告] {0}: 本机与期望的官方版本不一致"] = "  [Warning] {0}: the local and expected official versions differ";
        d["  [警告] 产物解析失败（不影响导入）: "] = "  [Warning] failed to parse the product (does not affect the import): ";
        d["  [警告] 写外部 ntl-console.lua 失败: "] = "  [Warning] failed to write the external ntl-console.lua: ";
        d["  [警告] 包内缺少文件: "] = "  [Warning] missing file in the package: ";
        d["  [警告] 包名与 mod.json 都没有章节提示（chapterN / root）。"] = "  [Warning] neither the package name nor mod.json carries a chapter hint (chapterN / root).";
        d["  [警告] 合并清单写入失败: {0}"] = "  [Warning] failed to write the merge manifest: {0}";
        d["  [警告] 基线与源是同一个文件 -> 按全量导出"] = "  [Warning] baseline and source are the same file -> exporting in full";
        d["  [警告] 备份失败: {0}"] = "  [Warning] backup failed: {0}";
        d["  [警告] 存档快照失败: {0}"] = "  [Warning] save snapshot failed: {0}";
        d["  [警告] 宿主 mod.json 解析失败（{0}），元数据按目录名推断"] = "  [Warning] host mod.json parse failed ({0}); inferring metadata from the directory name";
        d["  [警告] 循环依赖，剩余按原顺序: "] = "  [Warning] circular dependency; the rest keep the original order: ";
        d["  [警告] 暂存目录清理失败（可手工删）: {0} — {1}"] = "  [Warning] failed to clean the staging directory (delete it manually): {0} — {1}";
        d["  [警告] 未找到 xdelta3.exe（应在 <游戏根>/xdelta/xdelta3.exe）"] = "  [Warning] xdelta3.exe not found (expected at <game root>/xdelta/xdelta3.exe)";
        d["  [警告] 未找到预期产物目录 {0}，跳过合并清单写入（转换本身已成功）"] = "  [Warning] expected product directory {0} not found; skipping the merge manifest write (the conversion itself succeeded)";
        d["  [警告] 未知 patch 类型: {0} → {1}"] = "  [Warning] unknown patch type: {0} → {1}";
        d["  [警告] 没找到中文字体源，控制台中文会缺字"] = "  [Warning] no Chinese font source found; the console will be missing Chinese glyphs";
        d["  [警告] 覆盖失败 {0}: {1}"] = "  [Warning] overwrite failed {0}: {1}";
        d["  [警告] 解包失败 {0}: {1}"] = "  [Warning] unpack failed {0}: {1}";
        d["  [错误] "] = "  [Error] ";
        d["  [错误] KristalImport 返回 {0}，转换失败。现场保留: {1}"] = "  [Error] KristalImport returned {0}; conversion failed. Kept for inspection: {1}";
        d["  [错误] gameRoot 为空"] = "  [Error] gameRoot is empty";
        d["  [错误] mod.json 为空"] = "  [Error] mod.json is empty";
        d["  [错误] mod.json 解析失败: {0}"] = "  [Error] mod.json parse failed: {0}";
        d["  [错误] xdelta 失败 (exit={0}): {1}"] = "  [Error] xdelta failed (exit={0}): {1}";
        d["  [错误] xdelta 调用异常: "] = "  [Error] xdelta invocation exception: ";
        d["  [错误] 包里没有 main.lua，无法挂启动钩子"] = "  [Error] the package has no main.lua; cannot attach the startup hook";
        d["  [错误] 合并导入异常: {0}: {1}"] = "  [Error] merge import exception: {0}: {1}";
        d["  [错误] 基线 data.win 不存在: {0}"] = "  [Error] baseline data.win does not exist: {0}";
        d["  [错误] 宿主缺少 mod.json: {0}"] = "  [Error] the host is missing mod.json: {0}";
        d["  [错误] 宿主项目应为目录，却收到文件: {0}"] = "  [Error] the host project should be a directory, but a file was given: {0}";
        d["  [错误] 宿主项目目录不存在: {0}"] = "  [Error] host project directory does not exist: {0}";
        d["  [错误] 找不到 {0}"] = "  [Error] cannot find {0}";
        d["  [错误] 未指定宿主项目目录"] = "  [Error] no host project directory specified";
        d["  [错误] 未提供任何插件目录（至少要给一个插件型 Kristal mod）"] = "  [Error] no plugin directory given (at least one plugin-type Kristal mod is required)";
        d["  [错误] 没有任何插件被成功合并 —— 中止（不产出只有宿主的转换结果，避免误以为合并成功）"] = "  [Error] no plugin was merged successfully — aborting (we do not emit a host-only conversion result, to avoid the impression that the merge worked)";
        d["  [错误] 注入失败: "] = "  [Error] injection failed: ";
        d["  [错误] 源 data.win 不存在: {0}"] = "  [Error] source data.win does not exist: {0}";
        d["  [错误] 目录不存在: {0}"] = "  [Error] directory does not exist: {0}";
        d["  [错误] 缺少 mod.json: {0}"] = "  [Error] missing mod.json: {0}";
        d["  [错误] 缺少 {0}"] = "  [Error] missing {0}";
        d["  [错误] 缺少基线: "] = "  [Error] missing baseline: ";
        d["  [错误] 补丁与本机所有官方基线都不匹配（可能基于其它游戏版本）"] = "  [Error] the patch matches none of the local official baselines (it may be based on another game version)";
        d["  [错误] 裸 data.win 无法自动判定章节 —— 请用 --chapter chapterN 指定"] = "  [Error] cannot auto-detect the chapter of a bare data.win — specify it with --chapter chapterN";
        d["  [错误] 资源包导出失败: {0}: {1}"] = "  [Error] resource pack export failed: {0}: {1}";
        d["  [错误] 输出目录为空"] = "  [Error] output directory is empty";
        d["  [错误] 这个 exe 里没有 mods/*/mod.json —— 不是 Kristal 融合包？"] = "  [Error] no mods/*/mod.json inside this exe — is it not a Kristal fusion package?";
        d["  mod 根目录: {0}"] = "  mod root: {0}";
        d["  mod 目录 : "] = "  mod dir  : ";
        d["  mod 目录: "] = "  mod dir: ";
        d["  ~ main.lua 末尾挂启动钩子（{0} → {1} 字节）"] = "  ~ appending the startup hook to the end of main.lua ({0} → {1} bytes)";
        d["  → 单项补丁："] = "  → single patch: ";
        d["  → 检测到 Kristal 结构（mod.lua / engineVer / scripts+assets）：转交 --import-kristal"] = "  → Kristal structure detected (mod.lua / engineVer / scripts+assets): handing off to --import-kristal";
        d["  → 检测到 mod.json：原生 Neutraled mod，转交 --mod-install"] = "  → mod.json detected: a native Neutraled mod, handing off to --mod-install";
        d["  → 检测到成品程序（自带 exe + love/SDL 运行库，没有工程源码）"] = "  → standalone program detected (bundles an exe + love/SDL runtimes, no project source)";
        d["  ⚠️ 未实现的 API（会导致脚本失败）:"] = "  ⚠️ unimplemented APIs (they will make scripts fail):";
        d["  ✅ 写回 {0}（{1:F1} MB，{2} ms）"] = "  ✅ wrote back {0} ({1:F1} MB, {2} ms)";
        d["  ✅ 安装完成"] = "  ✅ Install complete";
        d["  ✅ 已从 {0} 还原 {1}"] = "  ✅ restored {1} from {0}";
        d["  ✅ 已恢复: {0}（原子替换，无中间状态）"] = "  ✅ restored: {0} (atomic replace, no intermediate state)";
        d["  ✅ 没有用到已知未实现的 API"] = "  ✅ no known unimplemented API was used";
        d["  下一步   : ntl-builder.exe --deploy --chapter root   （之后在章节选择器里就能看到它）"] = "  Next     : ntl-builder.exe --deploy --chapter root   (it will then show up in the chapter selector)";
        d["  下一步:"] = "  Next:";
        d["  下一步: 关闭游戏后运行 launch.ps1 部署并启动"] = "  Next: close the game, then run launch.ps1 to deploy and start";
        d["  下一步: 编辑 main.lua -> 关游戏 -> 运行 Neutraled\\launch.ps1"] = "  Next: edit main.lua -> close the game -> run Neutraled\\launch.ps1";
        d["  不支持: "] = "  unsupported: ";
        d["  产物: {0} MB  对象={1} 代码={2} 精灵={3} 声音={4}"] = "  Product: {0} MB  objects={1} code={2} sprites={3} sounds={4}";
        d["  共 {0} 个"] = "  {0} total";
        d["  加载顺序: "] = "  Load order: ";
        d["  包: "] = "  Package: ";
        d["  包: {0}"] = "  Package: {0}";
        d["  包内文件:"] = "  Files in package:";
        d["  原因: .csx 必须由 UndertaleModTool 运行 C# 脚本才能产出修改后的 data.win；"] = "  Reason: a .csx must be run as a C# script by UndertaleModTool to produce the modified data.win;";
        d["  原状态已备份为 before-restore-*.zip，如需撤销可用它"] = "  the original state was backed up as before-restore-*.zip; use it to undo";
        d["  发现 UTMT C# 脚本（.csx）:"] = "  Found UTMT C# scripts (.csx):";
        d["  发现源码脚本（.cs/.py），但没有编译产物 data.win。"] = "  Found source scripts (.cs/.py), but no compiled data.win product.";
        d["  可执行   : "] = "  Executable: ";
        d["  可用模板: "] = "  Available templates: ";
        d["  可行路径（2 步，手工一次即可）:"] = "  Workable route (2 steps, one manual pass):";
        d["  合并完成: {0} 个插件 → 交给 KristalImport 整体转换"] = "  Merge complete: {0} plugins → handed to KristalImport for the whole conversion";
        d["  合并清单: {0}"] = "  Merge manifest: {0}";
        d["  合并统计: 插件 {0} 个 / scripts {1} 个 / assets {2} 个 / 上提资源 {3} 个 / 冲突 {4} 处"] = "  Merge stats: {0} plugins / {1} scripts / {2} assets / {3} hoisted resources / {4} conflicts";
        d["  名称: {0}  作者: {1}  版本: {2}  id: {3}"] = "  Name: {0}  author: {1}  version: {2}  id: {3}";
        d["  基线: "] = "  Baseline: ";
        d["  基线指纹: 精灵={0} 字体={1} 声音={2}"] = "  Baseline fingerprint: sprites={0} fonts={1} sounds={2}";
        d["  基线载入: 精灵={0} 声音={1} 字体={2}"] = "  Baseline loaded: sprites={0} sounds={1} fonts={2}";
        d["  备份原版 → {0}"] = "  Backing up vanilla → {0}";
        d["  存档基准快照已建立: BASELINE.zip（首次安装留底，永不删除）"] = "  Baseline save snapshot created: BASELINE.zip (kept from the first install, never deleted)";
        d["  存档快照: {0}（{1} KB）"] = "  Save snapshot: {0} ({1} KB)";
        d["  导出完成: 合计 {0} 个资源 ({1} ms) -> {2}"] = "  Export complete: {0} resources total ({1} ms) -> {2}";
        d["  已保存当前状态: {0}"] = "  Current state saved: {0}";
        d["  已安装到: {0}"] = "  Installed to: {0}";
        d["  已安装（版本 {0}）→ 将更新到 {1}"] = "  Already installed (version {0}) → will update to {1}";
        d["  已生成 Neutraled mod: {0}"] = "  Generated Neutraled mod: {0}";
        d["  已解压 {0} 个文件（{1}）"] = "  Extracted {0} files ({1})";
        d["  应用 xdelta: "] = "  Applying xdelta: ";
        d["  报告: {0}"] = "  Report: {0}";
        d["  描述: "] = "  Description: ";
        d["  文件: "] = "  File: ";
        d["  文件: {0} 个 .lua"] = "  Files: {0} .lua";
        d["  旧版本已备份: {0}"] = "  Old version backed up: {0}";
        d["  校验和 ✓（{0} 与清单期望一致）"] = "  Checksum ✓ ({0} matches the manifest)";
        d["  校验通过: 备份含 {0} 个文件"] = "  Verification passed: the backup contains {0} files";
        d["  格式 {0} / 章节 {1} / 成功 {2} / 失败 {3} / 覆盖文件 {4}"] = "  Format {0} / chapter {1} / ok {2} / failed {3} / overwritten files {4}";
        d["  格式: "] = "  Format: ";
        d["  模式: dry-run（只分析，不写盘）"] = "  Mode: dry-run (analyze only, nothing written)";
        d["  模板: "] = "  Templates: ";
        d["  注意     : 玩它需要守候进程（--watch-external）；已随安装器/开机自启一起提供"] = "  Note     : playing it requires the watcher process (--watch-external); provided with the installer / startup autostart";
        d["  源载入: 精灵={0} 声音={1} 字体={2}"] = "  Source loaded: sprites={0} sounds={1} fonts={2}";
        d["  激活 mod 目录: {0}"] = "  Active mod directory: {0}";
        d["  生成的文件:"] = "  Generated files:";
        d["  目录: "] = "  Directory: ";
        d["  目录: {0}"] = "  Directory: {0}";
        d["  目标游戏版本: "] = "  Target game version: ";
        d["  章节名   : "] = "  Chapter  : ";
        d["  章节由 --chapter 指定: "] = "  Chapter given by --chapter: ";
        d["  自动改写: "] = "  Auto-rewritten: ";
        d["  自动识别章节: {0}（{1}）"] = "  Auto-detected chapter: {0} ({1})";
        d["  裸 data.win（{0} MB）章节推断:"] = "  Bare data.win ({0} MB) chapter inference:";
        d["  覆盖文件: {0}"] = "  Overwritten files: {0}";
        d["  计划:"] = "  Plan:";
        d["  语法可疑: {0}"] = "  Suspicious syntax: {0}";
        d["  语法检查通过: {0}/{1}"] = "  Syntax check passed: {0}/{1}";
        d["  资源包导出(全量): {0} -> {1}"] = "  Resource pack export (full): {0} -> {1}";
        d["  资源包导出(差异): {0} - {1} -> {2}"] = "  Resource pack export (diff): {0} - {1} -> {2}";
        d["  输入: {0}"] = "  Input: {0}";
        d["  输出: "] = "  Output: ";
        d["  部署目标（叶子）: {0}"] = "  Deploy target (leaf): {0}";
        d["  需人工确认: "] = "  Needs manual review: ";
        d["  风险最高的脚本（共 {0} 个有风险）:"] = "  Highest-risk scripts ({0} risky in total):";
        d["  （{0} 条未处理）"] = "  ({0} unhandled)";
        d["  （无）"] = "  (none)";
        d["  （还没有备份）"] = "  (no backups yet)";
        d[" 个 .lua 文件..."] = " .lua files...";
        d[" 纹理页={0} ({1} ms)"] = " texture pages={0} ({1} ms)";
        d["===== Kristal 批量验证 ====="] = "===== Kristal batch verify =====";
        d["===== Kristal 转换完成 ====="] = "===== Kristal conversion complete =====";
        d["===== mod 安装 ====="] = "===== mod install =====";
        d["===== mod 骨架已生成 ====="] = "===== mod skeleton generated =====";
        d["===== 传统 mod 导入（转 ntl 格式） ====="] = "===== legacy mod import (convert to ntl format) =====";
        d["===== 存档备份 ====="] = "===== save backup =====";
        d["===== 导入结果 ====="] = "===== import result =====";
        d["===== 已安装的 mod ====="] = "===== installed mods =====";
        d["===== 给融合版 Kristal 注入控制台 ====="] = "===== injecting the console into a fused Kristal =====";
        d["[警告] mod_config.json 解析失败: "] = "[Warning] mod_config.json parse failed: ";
        d["[警告] modding.xml 解析失败: "] = "[Warning] modding.xml parse failed: ";
        d["[错误] 不支持的包类型: "] = "[Error] unsupported package type: ";
        d["[错误] 包里没有 mod.json（不是有效的 Neutraled/Kristal mod）"] = "[Error] the package has no mod.json (not a valid Neutraled/Kristal mod)";
        d["[错误] 备份是空的，已取消恢复（存档未改动）"] = "[Error] the backup is empty; restore cancelled (save untouched)";
        d["[错误] 恢复失败（已回滚，存档保持原样）: {0}"] = "[Error] restore failed (rolled back, save unchanged): {0}";
        d["[错误] 找不到包"] = "[Error] package not found";
        d["[错误] 找不到包: "] = "[Error] package not found: ";
        d["[错误] 找不到指定的备份"] = "[Error] specified backup not found";
        d["[错误] 没有备份目录"] = "[Error] no backup directory";
        d["[错误] 目录不存在: "] = "[Error] directory does not exist: ";
        d["[错误] 目录不存在: {0}"] = "[Error] directory does not exist: {0}";
        d["[错误] 目录已存在: "] = "[Error] directory already exists: ";
        d["[错误] 目录已存在: {0}"] = "[Error] directory already exists: {0}";
        d["[错误] 解压失败: "] = "[Error] extraction failed: ";
        d["[错误] 解压失败: {0}"] = "[Error] extraction failed: {0}";
        d["[错误] 请指定 mod 名字：--new-mod MyMod"] = "[Error] specify a mod name: --new-mod MyMod";
        d["[错误] 这个包不能自动转换 —— 包里没有可用的 data.win / xdelta 补丁。"] = "[Error] this package cannot be converted automatically — it has no usable data.win / xdelta patch.";
        d["] 输出"] = "] output";
        d["zip 起始偏移异常"] = "zip start offset is invalid";
        d["✓ 转换成功（外部引擎章节）"] = "✓ Converted successfully (external engine chapter)";
        d["压缩方式不支持: "] = "unsupported compression method: ";
        d["扫描 "] = "Scanning ";
        d["本地头损坏: "] = "corrupt local header: ";
        d["条目 {0} 用了 zip64，本工具不支持（避免写坏包）"] = "entry {0} uses zip64, which this tool does not support (to avoid corrupting the package)";
        d["没找到 zip 结束记录 —— 这不是融合版 LÖVE exe？"] = "no zip end record found — is this not a fused LÖVE exe?";
        d["自动探测章节"] = "auto-detect chapter";
    }
}
