namespace Neutraled.Builder;

/// <summary>英文译文表（Program 组）。key = 中文原文（含 {0} 占位符），value = 英文。
/// 由 tools 脚本从 _i18n-builder/keys-program.json 生成，**不要手改单个条目**。</summary>
public static class LangTable_Program
{
    public static void Fill(Dictionary<string, string> d)
    {
        d["                                    原版自动备份成 <exe>.orig，可反复注入）"] = "                                    The original is backed up as <exe>.orig, so injection can be repeated)";
        d["                                  fork       =复制一个已安装 mod 章节当基底（配合 --fork）"] = "                                  fork       =Copy an installed mod chapter and use it as the base (with --fork)";
        d["                                  independent=自带 data.win 的独立章节（默认）"] = "                                  independent=Standalone chapter that ships its own data.win (default)";
        d["                                  overlay    =只叠加到官方某章，不产生新章节条目"] = "                                  overlay    =Overlay onto one official chapter only; no new chapter entry";
        d["                                  并负责隐藏/恢复 DELTARUNE 窗口 + 把焦点交给外部引擎"] = "                                  and handles hiding / restoring the DELTARUNE window + handing focus to the external engine";
        d["                                  （往内嵌 zip 追加 src/ntlconsole.lua + 在 main.lua 挂启动钩子；"] = "                                  (appends src/ntlconsole.lua to the embedded zip + hooks startup in main.lua;";
        d["         代价：章节内『控制台输入屏蔽』失效 —— 控制台仍能打开，但游戏自身的 keyboard_check_direct 仍会读到按键"] = "         Cost: 'console input blocking' no longer works inside chapters -- the console still opens, but the game's own keyboard_check_direct still sees the keys";
        d["         应放在 mods/<mod名>/<作者>/data/{0}/data.win（每个时间线一份）"] = "         Goes in mods/<mod>/<author>/data/{0}/data.win (one per timeline)";
        d["         想强制完整档：加 --full-deploy"] = "         To force the full path, add --full-deploy";
        d["        → 想换基底：--base-mod <id>；其余 mod 的脚本/资源/files 覆盖仍会生效"] = "        → To switch the base: --base-mod <id>; the scripts / assets / files overrides of other mods still apply";
        d["      --author <作者>             作者名（默认 Player）→ mods/<名字>/<作者>/"] = "      --author <author>         Author name (default Player) → mods/<name>/<author>/";
        d["      --chapter <ch>              指定章节（不给则从路径推断）"] = "      --chapter <ch>              Target chapter (inferred from the path if omitted)";
        d["      --chapter <chapterN>        基底官方章节（默认 chapter1）"] = "      --chapter <chapterN>        Base official chapter (default chapter1)";
        d["      --diff-override             层与层改同一对象时，声明 later-wins"] = "      --diff-override             When two layers change the same object, declare later-wins";
        d["      --dry-run                   只分析不写盘（配合 --import-mod 做预检）"] = "      --dry-run                   Analyze only, write nothing (pair with --import-mod for a dry check)";
        d["      --fork <mod>[:作者[:chapterN]]  被 fork 的源章节（--new-chapter help 可列清单）"] = "      --fork <mod>[:author[:chapterN]]  Source chapter to fork (--new-chapter help lists them)";
        d["      --mod-force                 校验和不符时仍强制尝试"] = "      --mod-force                 Force the attempt even when checksums do not match";
        d["      --model Mod|Wip             指定 GameBanana 条目类型（默认 Mod）"] = "      --model Mod|Wip             GameBanana entry type (default Mod)";
        d["      --name <名> --author <作者>  覆盖包内元数据"] = "      --name <name> --author <author>  Override the metadata inside the package";
        d["      --out <目录>                指定输出目录（默认写进对应 mod 目录）"] = "      --out <dir>               Output directory (defaults to the matching mod directory)";
        d["      --slot <N>                  章节排序号（默认自动排在最后，最小 6）"] = "      --slot <N>                  Chapter sort number (appended last by default, minimum 6)";
        d["      --template room|empty       模板：room=带一个可走房间（默认）/ empty=空骨架"] = "      --template room|empty       Template: room = ships one walkable room (default) / empty = bare skeleton";
        d["     前台={0}（目标 pid {1}）"] = "     Foreground={0} (target pid {1})";
        d["     玩完关掉外部引擎后，会自动把 DELTARUNE 拉回章节选择"] = "     Closing the external engine when you are done automatically pulls DELTARUNE back to the chapter selector";
        d["    复制配置+存档: {0} 个"] = "    Copied config + saves: {0}";
        d["    外部章节增量复制: 更新 {0} / 未变跳过 {1}"] = "    External chapter incremental copy: updated {0} / unchanged skipped {1}";
        d["  --add-external <exe> [名字]     注册成外部章节（章节选择器里可选）"] = "  --add-external <exe> [name]     Register as an external chapter (selectable in the chapter selector)";
        d["  --api-doc                       生成 API 文档"] = "  --api-doc                       Generate the API docs";
        d["  --conflicts                     只查 mod 冲突不部署（0=无冲突 / 2=有冲突，CI 友好）"] = "  --conflicts                     Only check mod conflicts, no deploy (0=no conflicts / 2=conflicts, CI friendly)";
        d["  --deploy --chapter chapter4     部署核心+mods 到章节"] = "  --deploy --chapter chapter4     Deploy core + mods to a chapter";
        d["  --export-packs <data.win>       导出资源包（精灵/声音/字体）→ 可叠加到任意基底"] = "  --export-packs <data.win>       Export asset packs (sprites / sounds / fonts) → can be overlaid on any base";
        d["  --extract-diff <data.win|目录>  把整包 mod 提取成**可叠加的差异层**（让多个整包 mod 共存）"] = "  --extract-diff <data.win|dir>   Extract a full-package mod into an **overlayable diff layer** (so several full-package mods can coexist)";
        d["  --fetch-mod <gamebananaId>      下载 + 自动识别格式转换（含 Kristal）"] = "  --fetch-mod <gamebananaId>      Download + auto-detect and convert the format (Kristal included)";
        d["  --focus-test <exe> [--send-f2] [--keep]   焦点抢占自检（后台进程能否抢到前台 + F2 是否打开控制台）"] = "  --focus-test <exe> [--send-f2] [--keep]   Focus-grab self-test (can a background process take the foreground + does F2 open the console)";
        d["  --import-delta <xdelta>         单项 xdelta / 修改版 data.win 转换"] = "  --import-delta <xdelta>         Single xdelta / modified data.win conversion";
        d["  --import-mod <包|目录>          传统 mod 自动转 ntl 格式（modding.xml / meta.toml / xdelta / zip / 原生 mod）"] = "  --import-mod <pkg|dir>          Auto-convert a classic mod to ntl format (modding.xml / meta.toml / xdelta / zip / native mod)";
        d["  --info   --chapter chapter4     显示 data.win 概要"] = "  --info   --chapter chapter4     Show a data.win summary";
        d["  --kristal-console [exe]         给**没有源码的融合版 Kristal exe** 注入 Neutraled 控制台"] = "  --kristal-console [exe]         Inject the Neutraled console into a **fused Kristal exe with no source code**";
        d["  --kristal-console-restore [exe] 从 .orig 还原（撤销注入）"] = "  --kristal-console-restore [exe] Restore from .orig (undo the injection)";
        d["  --kristal-merge <项目> --with <插件>...   Kristal 宿主合并导入（插件型 mod 缺宿主）"] = "  --kristal-merge <project> --with <plugin>...   Kristal host merge import (for plugin-type mods with no host)";
        d["  --lang zh|en                    设置输出语言（默认跟随 config.json 的 lang，缺省 zh；也可用环境变量 NTL_LANG）"] = "  --lang zh|en                    Set the output language (defaults to config.json lang, zh if unset; the NTL_LANG environment variable also works)";
        d["  --layer-from-base <data.win>    **源码级**差异层：反编译真实改动对象 → GML patch（不再受索引移植限制）"] = "  --layer-from-base <data.win>    **Source-level** diff layer: decompile the really-changed objects → GML patch (no longer limited by index porting)";
        d["  --lint / --doctor / --smoke     静态检查 / 自检 / API 冒烟"] = "  --lint / --doctor / --smoke     Static check / self-test / API smoke";
        d["  --mod-install <包>              安装原生 Neutraled/Kristal mod 包"] = "  --mod-install <pkg>             Install a native Neutraled/Kristal mod package";
        d["  --mod-list                      列出已安装 mod"] = "  --mod-list                      List installed mods";
        d["  --new-chapter <名字>            生成一个**能进、能走、能看**的自定义章节（默认独立章节）"] = "  --new-chapter <name>            Generate a custom chapter that **loads, walks and renders** (standalone chapter by default)";
        d["  --probe-code <data.win> <对象名>   指令级取证（字段真实类型 + 解析目标）"] = "  --probe-code <data.win> <obj>   Instruction-level forensics (real field types + resolved targets)";
        d["  --selftest [--no-launch]        端到端自测"] = "  --selftest [--no-launch]        End-to-end self-test";
        d["  --verify --chapter chapter4     校验注入结果"] = "  --verify --chapter chapter4     Verify the injection result";
        d["  --verify-refcopy <源> <目标>      用反编译器当预言机，验证跨资源池复制是否保真"] = "  --verify-refcopy <src> <dst>    Use the decompiler as an oracle to check whether cross-pool copies are faithful";
        d["  --watch-external                守候进程（静默，无窗口）：看到启动请求就拉起外部引擎，"] = "  --watch-external                Watcher process (silent, no window): launches the external engine when it sees a launch request,";
        d["  [OK] {0}: {1}x{2} 格 "] = "  [OK] {0}: {1}x{2} tiles ";
        d["  [kristal] 中文回退已就绪（{0} 个字体配置）"] = "  [kristal] CJK fallback ready ({0} font configs)";
        d["  [kristal] 已放入中文字体 {0} → assets/fonts/ntl_cjk.ttf"] = "  [kristal] Placed CJK font {0} → assets/fonts/ntl_cjk.ttf";
        d["  [kristal] 找不到可用的中文字体，跳过中文回退（菜单中文可能缺失）"] = "  [kristal] No usable CJK font found; skipping the CJK fallback (CJK menu text may be missing)";
        d["  [{0}] {1}  (id={2}, 作者={3}, 下载={4})"] = "  [{0}] {1}  (id={2}, author={3}, downloads={4})";
        d["  [外部章节] {0} → {1}"] = "  [External] {0} → {1}";
        d["  [失败] {0}: {1}"] = "  [Failed] {0}: {1}";
        d["  [失败] {0}（exit={1}）"] = "  [Failed] {0} (exit={1})";
        d["  [异常] {0}: {1}"] = "  [Exception] {0}: {1}";
        d["  [恢复] DELTARUNE 窗口处于隐藏状态 → 接管监视：{0}"] = "  [Restore] The DELTARUNE window is hidden → taking over monitoring: {0}";
        d["  [恢复] 外部引擎已退出 → 恢复游戏窗口并交还控制权"] = "  [Restore] The external engine exited → restoring the game window and handing back control";
        d["  [恢复] 异常: "] = "  [Restore] Exception: ";
        d["  [恢复] 窗口是隐藏的，但 chapters.json 里没有外部章节 → 不动它（避免误恢复）"] = "  [Restore] The window is hidden, but chapters.json has no external chapter → leaving it alone (to avoid a wrong restore)";
        d["  [恢复] 跳过: "] = "  [Restore] Skipped: ";
        d["  [提示] 产物 {0} MB，跳过自动自检（要检查请加 --self-check，约 +9 秒）"] = "  [Tip] Output is {0} MB, skipping the automatic self-check (pass --self-check to run it, about +9 s)";
        d["  [提示] 没等到外部引擎窗口，无法自动聚焦（手动点一下即可）"] = "  [Tip] The external engine window never appeared; cannot focus automatically (click it once manually)";
        d["  [警告] curl 通道失败，回退 .NET HttpClient"] = "  [Warning] The curl channel failed, falling back to .NET HttpClient";
        d["  [警告] 下载失败: "] = "  [Warning] Download failed: ";
        d["  [警告] 依赖分析失败: {0}"] = "  [Warning] Dependency analysis failed: {0}";
        d["  [警告] 写回程标记失败: "] = "  [Warning] Failed to write the return marker: ";
        d["  [警告] 冲突分析失败: {0}"] = "  [Warning] Conflict analysis failed: {0}";
        d["  [警告] 启动外部引擎失败: {0}"] = "  [Warning] Failed to launch the external engine: {0}";
        d["  [警告] 启动失败: {0}"] = "  [Warning] Launch failed: {0}";
        d["  [警告] 启动请求缺少 exe"] = "  [Warning] The launch request has no exe";
        d["  [警告] 外部章节 {0} 安装失败: {1}"] = "  [Warning] External chapter {0} failed to install: {1}";
        d["  [警告] 外部章节 {0}: 保留的项目目录不存在 {1}"] = "  [Warning] External chapter {0}: the kept project directory does not exist {1}";
        d["  [警告] 外部运行标记写入失败: "] = "  [Warning] Failed to write the external-running marker: ";
        d["  [警告] 拉回游戏失败: {0}（手动开一下即可）"] = "  [Warning] Failed to pull the game back: {0} (just start it manually)";
        d["  [警告] 权限分析失败: {0}"] = "  [Warning] Permission analysis failed: {0}";
        d["  [警告] 聚焦线程异常: "] = "  [Warning] Focus thread exception: ";
        d["  [警告] 部署后自检异常（不影响部署）: {0}"] = "  [Warning] Post-deploy self-check threw (the deploy is unaffected): {0}";
        d["  [警告] 配置 Kristal 中文回退失败: {0}"] = "  [Warning] Failed to configure the Kristal CJK fallback: {0}";
        d["  [警告] 音频目录处理失败: {0}"] = "  [Warning] Failed to handle the audio directory: {0}";
        d["  [警告] 音频目录联接失败"] = "  [Warning] Audio directory junction failed";
        d["  [跳过] {0}: 基底章节不可用 {1}"] = "  [Skip] {0}: base chapter unavailable {1}";
        d["  [跳过] {0}: 找不到声明的 mod（{1}）"] = "  [Skip] {0}: declared mod not found ({1})";
        d["  [跳过] {0}: 被引用章节产物不存在 {1}"] = "  [Skip] {0}: the referenced chapter output does not exist {1}";
        d["  [适配] {0}: {1}"] = "  [Compat] {0}: {1}";
        d["  [适配] {0}: 声明『仅资源』但实际带了 {1} 个 patch / "] = "  [Compat] {0}: declared 'assets only' but actually ships {1} patch(es) / ";
        d["  [适配] {0}: 声明『无 hook』但实际有 {1} 条 hook 声明 → **忽略该声明**"] = "  [Compat] {0}: declared 'no hooks' but actually has {1} hook declarations → **declaration ignored**";
        d["  [适配] {0}: 声明章节 {1} 与实际所在章节 {2} 不符 → **忽略该声明**"] = "  [Compat] {0}: declared chapter {1} but actually lives in chapter {2} → **declaration ignored**";
        d["  [适配] ✅ 全部启用 mod 都声明兼容快速档 → 自动走快速通道（跳过输入重定向，约省 20 秒）"] = "  [Compat] ✅ every enabled mod declares fast-deploy support → taking the fast path (skips input redirection, saves about 20 s)";
        d["  [适配] 全部 mod 都声明兼容快速档，但玩家指定了 --full-deploy → 仍走完整档"] = "  [Compat] every mod declares fast-deploy support, but the player passed --full-deploy → using the full path";
        d["  [适配] 已是快速档（--fast-deploy）"] = "  [Compat] Already on the fast path (--fast-deploy)";
        d["  [错误] {0}: {1}"] = "  [Error] {0}: {1}";
        d["  [错误] {0}「{1}」: 平行时间线缺少自带 data"] = "  [Error] {0} '{1}': the parallel timeline is missing its own data";
        d["  [错误] 导出失败"] = "  [Error] Export failed";
        d["  [错误] 没指定 exe"] = "  [Error] No exe specified";
        d["  [错误] 没指定 exe，也没有已注册的外部章节。用法: --kristal-console <exe>"] = "  [Error] No exe specified, and no external chapter is registered. Usage: --kristal-console <exe>";
        d["  [错误] 部署后自检未通过 —— 产物可能不可用，已中止（不会静默放过）"] = "  [Error] Post-deploy self-check failed -- the output may be unusable; aborted (not silently ignored)";
        d["  api 指纹    : {0}"] = "  api fingerprint : {0}";
        d["  obj_ntl_core 对象: {0}"] = "  obj_ntl_core object: {0}";
        d["  scr_ntl_init 脚本: {0}"] = "  scr_ntl_init script: {0}";
        d["  ⏳ 无匹配缓存 → 开始部署..."] = "  ⏳ No matching cache → starting deploy...";
        d["  ⏳ 无缓存    : 这次启动会真正部署一遍，然后把结果存进缓存"] = "  ⏳ No cache    : this launch does a real deploy, then stores the result in the cache";
        d["  ▶ 外部章节「{0}」→ 启动 {1} {2}"] = "  ▶ External chapter '{0}' → launching {1} {2}";
        d["  ▶ 游戏已启动，守候中..."] = "  ▶ Game started, watching...";
        d["  ◀ 外部引擎已退出"] = "  ◀ The external engine exited";
        d["  ◀ 游戏暂时不在运行 —— 继续守候（等它回来）"] = "  ◀ The game is not running right now -- keep watching (until it comes back)";
        d["  ⚠ 检测到游戏弹出的对话框（Code Error）—— 已显示出来，请查看"] = "  ⚠ Detected a game dialog (Code Error) -- shown it, please take a look";
        d["  ⚠ 自动聚焦失败 —— 请手动点一下外部引擎窗口"] = "  ⚠ Auto-focus failed -- please click the external engine window once";
        d["  ✅ 命中缓存  : {0} MB，用过 {1} 次，建于 {2}  → 启动会硬链接秒开"] = "  ✅ Cache hit   : {0} MB, used {1} times, built {2}  → launching via hardlinks (instant)";
        d["  ✅ 已启动（Kristal 用的是它自己的存档目录）"] = "  ✅ Started (Kristal uses its own save directory)";
        d["  ✅ 已请求 Steam 启动 DELTARUNE"] = "  ✅ Asked Steam to launch DELTARUNE";
        d["  ✅ 已通知常驻中的 DELTARUNE 回到前台（0 秒回程）"] = "  ✅ Told the resident DELTARUNE to come back to the foreground (0-second return)";
        d["  ✅ 游戏已被关闭 → 已请求 Steam 重新启动（这次要等引擎初始化 ≈33s）"] = "  ✅ The game was closed → asked Steam to relaunch it (this time it waits for engine init, ≈33s)";
        d["  ✅ 焦点已交给外部引擎窗口（pid {0}，{1}）"] = "  ✅ Focus handed to the external engine window (pid {0}, {1})";
        d["  ✅ 缓存命中（{0} MB，第 {1} 次使用）: 硬链接 {2} 个文件（0 秒）"] = "  ✅ Cache hit ({0} MB, use #{1}): hardlinked {2} files (0 s)";
        d["  ✅ 部署完成并已存入缓存"] = "  ✅ Deploy complete, result stored in the cache";
        d["  下一步：--deploy 会自动导入（Neutraled/fonts/*.json）"] = "  Next: --deploy imports automatically (Neutraled/fonts/*.json)";
        d["  下次部署（--deploy-all）后即可在章节选择器里看到它；选中后会退出 DELTARUNE 并拉起该程序。"] = "  It shows up in the chapter selector after the next deploy (--deploy-all); selecting it exits DELTARUNE and launches that program.";
        d["  下载: {0}  {1} KB"] = "  Downloading: {0}  {1} KB";
        d["  从零做自己的章节（GML 模板 + 脚手架，详见 docs/CHAPTER_DEV.md）:"] = "  Build your own chapter from scratch (GML template + scaffold, see docs/CHAPTER_DEV.md):";
        d["  例: ntl-builder.exe --new-chapter \"我的章节\" --deploy --chapter root --force"] = "  Example: ntl-builder.exe --new-chapter 'My Chapter' --deploy --chapter root --force";
        d["  依赖 OK: {0} ← {1} {2} {3}（当前 {4}）"] = "  Dependency OK: {0} ← {1} {2} {3} (current {4})";
        d["  内容级自检抛异常: "] = "  Content-level self-check threw: ";
        d["  分发方式：把该文件放到 mods/<mod_name>/ 下即可被自动识别（无需解压）"] = "  Distribution: drop that file into mods/<mod_name>/ and it is picked up automatically (no extraction needed)";
        d["  启动游戏（通过 Steam）..."] = "  Launching the game (via Steam)...";
        d["  启用 mod    : {0} 个"] = "  Enabled mods    : {0}";
        d["  在游戏里进入 Kristal 章节时会自动拉起它自己的引擎（关掉本窗口即停止守候）"] = "  Entering the Kristal chapter in-game launches its own engine (closing this window stops the watcher)";
        d["  基底: 自带 data -> {0}"] = "  Base: own data -> {0}";
        d["  基底改动对象: {0} 个"] = "  Base-changed objects: {0}";
        d["  基底改动对象: {0} 个（命中缓存）"] = "  Base-changed objects: {0} (cache hit)";
        d["  基线: "] = "  Baseline: ";
        d["  外部文件覆盖: {0} 个（已备份到 .backup_files/{1}）"] = "  External file overrides: {0} (backed up to .backup_files/{1})";
        d["  外部章节（Kristal / 冰封帷幕这类成品）:"] = "  External chapters (finished products like Kristal / Frostveil):";
        d["  存档目录联接: {0} -> {1}"] = "  Save directory junction: {0} -> {1}";
        d["  存档联接已存在: {0} -> {1}"] = "  Save junction already exists: {0} -> {1}";
        d["  对象={0} 代码={1} 精灵={2} 脚本={3}"] = "  objects={0} code={1} sprites={2} scripts={3}";
        d["  导入 mod（全部自动识别包形态）:"] = "  Import mod (every package shape is auto-detected):";
        d["  导出资源总数: {0}"] = "  Exported resources: {0}";
        d["  已下载: {0}  ({1} KB)"] = "  Downloaded: {0}  ({1} KB)";
        d["  已写出: {0}"] = "  Written: {0}";
        d["  引导 {0}: {1}"] = "  Bootstrap {0}: {1}";
        d["  未检测到游戏目录：可用 --game \"<游戏目录>\" 指定后再查看游戏版本"] = "  Game directory not detected: pass --game '<game dir>' and try again to see the game version";
        d["  游戏版本    : {0}"] = "  Game version    : {0}";
        d["  状态签名    : {0}  (完整 {1} 字符)"] = "  State signature : {0}  (full {1} chars)";
        d["  章节        : {0}"] = "  Chapter         : {0}";
        d["  签名: {0}  目标: {1}"] = "  Signature: {0}  Target: {1}";
        d["  缓存条目    : {0} 个，上限 {1} MB"] = "  Cache entries   : {0}, max {1} MB";
        d["  质量与自检:"] = "  Quality and self-check:";
        d["  运行时文件复制: {0} 个"] = "  Runtime file copies: {0}";
        d["  退出码约定: 0=无冲突 / 2=有 {0} 个 Error 级冲突"] = "  Exit codes: 0=no conflicts / 2={0} Error-level conflicts";
        d["  适配汇总: {0}/{1} 个 mod 带适配声明；"] = "  Compat summary: {0}/{1} mods carry compat declarations; ";
        d["  音频目录联接: {0} -> {1}"] = "  Audio directory junction: {0} -> {1}";
        d["  （{0} 个 api 脚本）"] = "  ({0} api scripts)";
        d["  （多个文件时取最大的那个作为主包）"] = "  (with several files, the largest one is used as the main package)";
        d["  （被自动启用的 mod 是因为别的 mod 依赖它）"] = "  (auto-enabled mods are enabled because other mods depend on them)";
        d["(bytecode {0}, 文件名 {1})  "] = "(bytecode {0}, file {1})  ";
        d["--- {0}  「{1}」 <- {2}（运行时文件取自 {3}）+ {4} 个 mod ---"] = "--- {0}  '{1}' <- {2} (runtime files from {3}) + {4} mods ---";
        d["... (截断)"] = "... (truncated)";
        d["...(截断)"] = "...(truncated)";
        d["===== Neutraled 启动器 ====="] = "===== Neutraled launcher =====";
        d["===== 下载并导入 GameBanana mod {0} ====="] = "===== Download and import GameBanana mod {0} =====";
        d["===== 全部完成: {0}/{1} 章成功 ====="] = "===== All done: {0}/{1} chapters succeeded =====";
        d["===== 共 {0} 份，占用 {1} MB / {2} MB ====="] = "===== {0} entries, using {1} MB / {2} MB =====";
        d["===== 冲突报告（{0}，{1} 个启用的 mod）====="] = "===== Conflict report ({0}, {1} enabled mods) =====";
        d["===== 启动缓存查验（不启动游戏）====="] = "===== Launch cache check (does not start the game) =====";
        d["===== 外部章节守候 ====="] = "===== External chapter watcher =====";
        d["===== 完成: {0} 成功 / {1} 失败 ====="] = "===== Done: {0} succeeded / {1} failed =====";
        d["===== 平行时间线 / 引用章: {0} 个 ====="] = "===== Parallel timelines / referenced chapters: {0} =====";
        d["===== 把 {0} 个存档目录搬到游戏目录 ====="] = "===== Moving {0} save directories into the game directory =====";
        d["===== 时间线部署完成: {0}/{1} ====="] = "===== Timeline deploy complete: {0}/{1} =====";
        d["===== 缓存去重 ====="] = "===== Cache dedup =====";
        d["===== 资源包导出 =====\n  章节: {0}\n  输出: {1}"] = "===== Pack export =====\n  Chapter: {0}\n  Output: {1}";
        d["===== 转换 Kristal 地图: {0} 张 ====="] = "===== Converting Kristal maps: {0} =====";
        d["===== 部署 {0} ====="] = "===== Deploying {0} =====";
        d["===== 部署缓存（上限 {0} MB）====="] = "===== Deploy cache (limit {0} MB) =====";
        d["[1/5] 原版备份已存在（复用）"] = "[1/5] Original backup already exists (reused)";
        d["[1/5] 备份原版 -> {0}"] = "[1/5] Backing up the original -> {0}";
        d["[2/5] [警告] --base-mod {0} 没匹配到整包 mod，回退默认选择"] = "[2/5] [Warning] --base-mod {0} matched no full-package mod, falling back to the default pick";
        d["[2/5] [警告] {0} 个 mod 提供整包 data.win，本章只能用 1 个基底："] = "[2/5] [Warning] {0} mods offer a full data.win, but this chapter can only use 1 base:";
        d["[2/5] 基底: {0} 的 {1}（资源型基底）"] = "[2/5] Base: {1} from {0} (asset-type base)";
        d["[2/5] 基底: 原版备份"] = "[2/5] Base: original backup";
        d["[2/5] 基底: 引用的章节产物 {0}"] = "[2/5] Base: referenced chapter output {0}";
        d["[2/5] 基底取自 config.json base_mod: {0}"] = "[2/5] Base taken from config.json base_mod: {0}";
        d["[2/5] 基底由 --base-mod/config 指定: {0}"] = "[2/5] Base pinned by --base-mod/config: {0}";
        d["[3.5/5] 计算基底改动集合（冲突裁决用）..."] = "[3.5/5] Computing the base change set (used for conflict resolution)...";
        d["[3/5] mods: {0} 个（含基底 mod）"] = "[3/5] mods: {0} (including the base mod)";
        d["[4.5/5] 写盘前修复..."] = "[4.5/5] Pre-write repairs...";
        d["[4/5] 注入核心..."] = "[4/5] Injecting core...";
        d["[5/5] 写入 data.win..."] = "[5/5] Writing data.win...";
        d["[dump 失败] "] = "[dump failed] ";
        d["[存档] 独立存档名: {0} -> {1}（FileName + Name）"] = "[Save] Standalone save name: {0} -> {1} (FileName + Name)";
        d["[警告] API 注册表生成失败: {0}"] = "[Warning] Failed to generate the API registry: {0}";
        d["[警告] hook 注册表生成失败: {0}"] = "[Warning] Failed to generate the hook registry: {0}";
        d["[警告] {0} 依赖的 mod 不存在: {1}"] = "[Warning] {0} depends on a mod that does not exist: {1}";
        d["[警告] {0} 依赖的 mod 未启用: {1}"] = "[Warning] {0} depends on a mod that is not enabled: {1}";
        d["[警告] {0} 要求 {1} {2} {3}，但当前版本是 {4}"] = "[Warning] {0} requires {1} {2} {3}, but the current version is {4}";
        d["[警告] 创建运行期目录失败: {0}"] = "[Warning] Failed to create the runtime directory: {0}";
        d["[警告] 存档目录处理失败: {0}"] = "[Warning] Failed to handle the save directory: {0}";
        d["[警告] 存档目录联接失败: {0}"] = "[Warning] Save directory junction failed: {0}";
        d["[警告] 章节注册表生成失败: {0}"] = "[Warning] Failed to generate the chapter registry: {0}";
        d["[跳过] {0} 内容未变（签名 {1}）—— 产物已是这个内容，无需重新部署"] = "[Skip] {0} content unchanged (signature {1}) -- the output already has this content, no redeploy needed";
        d["[输出] 平行时间线产物 -> {0}"] = "[Output] Parallel timeline output -> {0}";
        d["[重做] {0} 内容未变（签名 {1}），但产物缺失（{2}）—— 必须重新部署才能生成"] = "[Redo] {0} content unchanged (signature {1}) but the output is missing ({2}) -- a redeploy is required to generate it";
        d["[重做] {0} 输入未变（签名 {1}），但产物内容对不上（记录 {2} / 当前 {3}）—— 产物被还原或替换过，必须重新部署"] = "[Redo] {0} inputs unchanged (signature {1}) but the output content does not match (recorded {2} / current {3}) -- the output was restored or replaced, a redeploy is required";
        d["[错误] "] = "[Error] ";
        d["[错误] {0}"] = "[Error] {0}";
        d["[错误] {0}: {1}"] = "[Error] {0}: {1}";
        d["[错误] 下载不完整（{0} / {1} 字节）—— 拒绝导入残缺的包"] = "[Error] Incomplete download ({0} / {1} bytes) -- refusing to import a truncated package";
        d["[错误] 下载失败"] = "[Error] Download failed";
        d["[错误] 找不到 mod: {0}（章节 {1}，作者 {2}）"] = "[Error] Mod not found: {0} (chapter {1}, author {2})";
        d["[错误] 找不到: {0}"] = "[Error] Not found: {0}";
        d["[错误] 没有找到 .tmx 地图"] = "[Error] No .tmx map found";
        d["[错误] 缺少原版备份: {0}"] = "[Error] Missing original backup: {0}";
        d["[错误] 部署 {0} 失败"] = "[Error] Failed to deploy {0}";
        d["bbox={0} sep={1} 掩码字节={2}"] = "bbox={0} sep={1} mask bytes={2}";
        d["data.win 与原版一致（跳过）"] = "data.win matches the original (skipped)";
        d["modId 必须是数字"] = "modId must be a number";
        d["{0,6} MB  命中 {1} 次  最后使用 {2}  "] = "{0,6} MB  hits {1}  last used {2}  ";
        d["{0}  {1}x{2}  帧={3}"] = "{0}  {1}x{2}  frames={3}";
        d["{0} 个 find_replace → **忽略该声明**（按完整通道）"] = "{0} find_replace entries → **declaration ignored** (using the full path)";
        d["{0}: {1}x{2}  帧={3}  原点=({4},{5})  "] = "{0}: {1}x{2}  frames={3}  origin=({4},{5})  ";
        d["{0}: 版本 {1}.{2}.{3}.{4}  "] = "{0}: version {1}.{2}.{3}.{4}  ";
        d["{0}: 读取失败 {1}"] = "{0}: read failed {1}";
        d["{0}完成: {1}/{2} 成功，总用时 {3:N1}s（并行度 {4}）"] = "{0} done: {1}/{2} succeeded, total {3:N1}s (parallelism {4})";
        d["✓ 完成: {0} 字形 / {1} 张 sheet，用时 {2:N1} 秒"] = "✓ Done: {0} glyphs / {1} sheets, took {2:N1} s";
        d["✓ 完成: 从 {0} 搬来 {1} 字形 / {2} 页，用时 {3:N1} 秒"] = "✓ Done: moved {1} glyphs / {2} pages from {0}, took {3:N1} s";
        d["✓ 已注册外部章节「{0}」（{1}）"] = "✓ Registered external chapter '{0}' ({1})";
        d["✓ 解压 {0} 个文件 → {1}（{2:N1}s）"] = "✓ Extracted {0} files → {1} ({2:N1}s)";
        d["下载: {0}"] = "Download: {0}";
        d["全部包都未变化，无需转换 ✓"] = "All packages unchanged, nothing to convert ✓";
        d["共 {0} 个匹配"] = "{0} matches in total";
        d["共 {0} 个匹配（总房间数 {1}）"] = "{0} matches in total ({1} rooms in total)";
        d["其中 {0} 个声明可在快速档运行（其余按完整通道）"] = "of which {0} declare fast-deploy support (the rest take the full path)";
        d["图层 {0} / 对象组 {1} "] = "layers {0} / object groups {1} ";
        d["存档实际位置: {0}"] = "Actual save location: {0}";
        d["导出 {0} 个代码条目 -> {1}"] = "Exported {0} code entries -> {1}";
        d["已下载: {0}"] = "Downloaded: {0}";
        d["已删除产物作用域清单 scope.json"] = "Deleted the output scope manifest scope.json";
        d["已删除运行时清单 mods.json"] = "Deleted the runtime manifest mods.json";
        d["已恢复原版 data.win <- {0}"] = "Restored the original data.win <- {0}";
        d["已打包: {0}  ({1:F1} MB)"] = "Packed: {0}  ({1:F1} MB)";
        d["已还原 {0} 个外部文件"] = "Restored {0} external files";
        d["并行{0}: {1} 项，并行度 {2}"] = "Parallel {0}: {1} items, parallelism {2}";
        d["恢复完成 ✓ {0} 已回到未部署状态"] = "Restore complete ✓ {0} is back in the undeployed state";
        d["找不到 {0}"] = "Cannot find {0}";
        d["找不到中文字体，请用 --ttf <路径> 指定（例：C:\\Windows\\Fonts\\simhei.ttf）"] = "No CJK font found; specify one with --ttf <path> (e.g. C:\\Windows\\Fonts\\simhei.ttf)";
        d["找不到压缩包: "] = "Package archive not found: ";
        d["找不到可执行文件: "] = "Executable not found: ";
        d["找不到目录: "] = "Directory not found: ";
        d["搜索 \"{0}\": {1} 条"] = "Search '{0}': {1} results";
        d["搬字形失败: "] = "Glyph move failed: ";
        d["文件列表（{0}）:"] = "File list ({0}):";
        d["未找到精灵: "] = "Sprite not found: ";
        d["没有找到存档目录"] = "No save directory found";
        d["游戏根: {0}"] = "Game root: {0}";
        d["生成中文字体包: {0} / {1}px / 字符集={2} → {3}"] = "Generating CJK font pack: {0} / {1}px / charset={2} → {3}";
        d["生成失败: "] = "Generation failed: ";
        d["目录里没有可导入的包: "] = "No importable package in the directory: ";
        d["目标 [{0}]"] = "Targets [{0}]";
        d["缓存上限已设为 {0} MB"] = "Cache limit set to {0} MB";
        d["缓存已清空: 删除 {0} 份"] = "Cache cleared: deleted {0} entries";
        d["该 mod 没有可下载文件"] = "This mod has no downloadable files";
        d["跳过 {0} 个未变化的包（内容+时间都没变，上次已成功导入）"] = "Skipped {0} unchanged packages (content and timestamp unchanged, already imported successfully)";
        d["输出目录: {0}"] = "Output directory: {0}";
        d["边距 L{0} R{1} T{2} B{3}  "] = "margin L{0} R{1} T{2} B{3}  ";
        d["部署完成 ✓  {0}  ({1} MB)"] = "Deploy complete ✓  {0}  ({1} MB)";
        d["验证 {0}:"] = "Verify {0}:";
        d["（差异导出）"] = "(diff export)";
        d["（无 → 全量导出）"] = "(none → full export)";
        d["  [错误] 窗口抢焦点只在 Windows 上可用（当前 {0}）"] = "  [error] stealing window focus is Windows-only (current: {0})";
    }
}
